"""
Futbolcu Bil - Soru Verileri
"""

ALL_QUESTIONS = [
    ("Genç yetenek mi?", "young", True),
    ("30 yaş üstü mü?", "over30", True),
    ("Sakallı mı?", "beard", True),
    ("Sarışın mı?", "blonde", True),
    ("Kel mi?", "bald", True),
    ("Saç bandı var mı?", "headband", True),
    ("Dövmesi var mı?", "tattoo", True),
    ("Ballon d'Or var mı?", "ballondor", True),
    ("100+ gol mü?", "goals100", True),
    ("Ş.Ligi kazandı mı?", "ucl", True),
    ("D.Kupası kazandı mı?", "worldcup", True),
    ("Kaptan mı?", "captain", True),
    ("Sol ayaklı mı?", "leftfoot", True),
    ("Avrupada mı?", "europe", True),
    ("SüperLig geçmişi?", "superlig", True),
    ("Afrikalı mı?", "african", True),
    ("10 numara mı?", "number10", True),
    ("9 numara mı?", "number9", True),
    ("7 numara mı?", "number7", True),
    ("Brezilyalı mı?", "nationality", "Brezilya"),
    ("Arjantinli mi?", "nationality", "Arjantin"),
    ("Türk mü?", "nationality", "Turkiye"),
    ("Fransız mı?", "nationality", "Fransa"),
    ("İngiliz mi?", "nationality", "Ingiltere"),
    ("Portekizli mi?", "nationality", "Portekiz"),
    ("Alman mı?", "nationality", "Almanya"),
    ("İspanyol mu?", "nationality", "Ispanya"),
    ("Polonyalı mı?", "nationality", "Polonya"),
    ("Belçikalı mı?", "nationality", "Belcika"),
    ("Hollandalı mı?", "nationality", "Hollanda"),
    ("Koreli mi?", "nationality", "G.Kore"),
    ("Norveçli mi?", "nationality", "Norvec"),
    ("Kolombiyalı mı?", "nationality", "Kolombiya"),
    ("Uruguaylı mı?", "nationality", "Uruguay"),
    ("İsveçli mi?", "nationality", "Isvec"),
    ("Boşnak mı?", "nationality", "Bosna"),
    ("Hırvat mı?", "nationality", "Hirvatistan"),
    ("İtalyan mı?", "nationality", "Italya"),
    ("Çek mi?", "nationality", "Cek Cumhuriyeti"),
    ("Danimarkalı mı?", "nationality", "Danimarka"),
    ("Ukraynalı mı?", "nationality", "Ukrayna"),
    ("Rus mu?", "nationality", "Rusya"),
    ("Macar mı?", "nationality", "Macaristan"),
    ("Kuzey İrlandalı mı?", "nationality", "Kuzey irlanda"),
    ("Şilili mi?", "nationality", "Sili"),
    ("Galli mi?", "nationality", "Galler"),
    ("Avrupalı mı?", "continent", "Avrupa"),
    ("G.Amerikalı mı?", "continent", "G.Amerika"),
    ("Afrikalı (kıta)?", "continent", "Afrika"),
    ("Asyalı mı?", "continent", "Asya"),
    ("Forvet mi?", "position", "Forvet"),
    ("Orta saha mı?", "position", "OrtaSaha"),
    ("Defans mı?", "position", "Defans"),
    ("Kaleci mi?", "position", "Kaleci"),
    ("LaLiga'da mı?", "league", "LaLiga"),
    ("Premier Lig'de mi?", "league", "Premier"),
    ("SüperLig'de mi?", "league", "SuperLig"),
    ("Suudi Lig'de mi?", "league", "Suudi"),
    ("Ligue 1'de mi?", "league", "Ligue1"),
    ("Serie A'da mı?", "league", "SerieA"),
    ("Bundesliga'da mı?", "league", "Bundesliga"),
    ("Emekli mi?", "league", "Emekli"),
    ("MLS'de mi?", "league", "MLS"),
]


def check_question(footballer, question_index):
    """Bir futbolcunun soruya cevabini kontrol eder"""
    text, key, value = ALL_QUESTIONS[question_index]
    if isinstance(value, bool):
        return footballer[key] == value
    return footballer[key] == value