QUESTIONS = {
    "futbol": {
        "kolay": [
            {"soru": "Bir futbol takımı sahada kaç kişiyle oynar?",
             "secenekler": ["A) 9", "B) 10", "C) 11", "D) 12"], "cevap": "C"},
            {"soru": "Futbol maçı kaç dakikadır?",
             "secenekler": ["A) 70", "B) 80", "C) 90", "D) 100"], "cevap": "C"},
            {"soru": "Penaltı kaç metreden atılır?",
             "secenekler": ["A) 9", "B) 10", "C) 11", "D) 12"], "cevap": "C"},
            {"soru": "Kırmızı kart gören oyuncu ne yapar?",
             "secenekler": ["A) Devam eder", "B) Sahadan atılır", "C) Yedek olur", "D) Kaptan olur"], "cevap": "B"},
            {"soru": "Dünya Kupası kaç yılda bir yapılır?",
             "secenekler": ["A) 2", "B) 3", "C) 4", "D) 5"], "cevap": "C"},
            {"soru": "Hangi pozisyondaki oyuncu kaleyi korur?",
             "secenekler": ["A) Forvet", "B) Orta saha", "C) Defans", "D) Kaleci"], "cevap": "D"},
            {"soru": "2022 Dünya Kupası nerede yapıldı?",
             "secenekler": ["A) Rusya", "B) Brezilya", "C) Katar", "D) Almanya"], "cevap": "C"},
            {"soru": "Sarı kart ne anlama gelir?",
             "secenekler": ["A) Oyundan atılma", "B) Uyarı", "C) Gol", "D) Ofsayt"], "cevap": "B"},
            {"soru": "Bir futbol maçında kaç devre vardır?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 4"], "cevap": "B"},
            {"soru": "Kaleci topu elle nerede tutabilir?",
             "secenekler": ["A) Her yerde", "B) Sadece ceza sahasında", "C) Sadece kornerde", "D) Hiçbir yerde"], "cevap": "B"},
            {"soru": "Futbol topunun standart çevresi kaç cm'dir?",
             "secenekler": ["A) 58-60", "B) 62-64", "C) 68-70", "D) 72-74"], "cevap": "C"},
            {"soru": "Ofsayt kuralı hangi bölgede geçerlidir?",
             "secenekler": ["A) Kendi yarı sahasında", "B) Rakip yarı sahasında", "C) Ceza sahasında", "D) Her yerde"], "cevap": "B"},
            {"soru": "Korner atışı nereden yapılır?",
             "secenekler": ["A) Ceza sahasından", "B) Orta sahadan", "C) Köşe noktasından", "D) Kale çizgisinden"], "cevap": "C"},
            {"soru": "Bir oyuncu kaç sarı kart görürse atılır?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 4"], "cevap": "B"},
            {"soru": "Futbol sahasının şekli nedir?",
             "secenekler": ["A) Kare", "B) Daire", "C) Dikdörtgen", "D) Üçgen"], "cevap": "C"},
            {"soru": "Taç atışı nasıl yapılır?",
             "secenekler": ["A) Ayakla", "B) Elle", "C) Kafayla", "D) Göğüsle"], "cevap": "B"},
            {"soru": "Maçın başlangıç vuruşu nereden yapılır?",
             "secenekler": ["A) Ceza sahasından", "B) Kornerden", "C) Orta noktadan", "D) Kale çizgisinden"], "cevap": "C"},
            {"soru": "Serbest vuruşta duvar kaç metre uzakta durmalıdır?",
             "secenekler": ["A) 7.32", "B) 9.15", "C) 11", "D) 5"], "cevap": "B"},
            {"soru": "Futbolda gol atınca skor kaç artar?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 6"], "cevap": "A"},
            {"soru": "Hangi renk kart uyarı anlamına gelir?",
             "secenekler": ["A) Kırmızı", "B) Mavi", "C) Yeşil", "D) Sarı"], "cevap": "D"},
            {"soru": "Futbolda 'gol' ne demektir?",
             "secenekler": ["A) Top sahadan çıktı", "B) Top kaleye girdi", "C) Faul yapıldı", "D) Ofsayt var"], "cevap": "B"},
            {"soru": "Devre arası kaç dakikadır?",
             "secenekler": ["A) 5", "B) 10", "C) 15", "D) 20"], "cevap": "C"},
            {"soru": "Futbol kaç kişiyle oynanır (toplam iki takım)?",
             "secenekler": ["A) 18", "B) 20", "C) 22", "D) 24"], "cevap": "C"},
            {"soru": "Hangi çizgi kaleyi belirler?",
             "secenekler": ["A) Orta çizgi", "B) Taç çizgisi", "C) Kale çizgisi", "D) Korner çizgisi"], "cevap": "C"},
            {"soru": "Futbolda kaç oyuncu yedek kulübesinde oturabilir?",
             "secenekler": ["A) 3", "B) 5", "C) 7", "D) Kurallara göre değişir"], "cevap": "D"},
            {"soru": "Fenerbahçe kaç yılında kurulmuştur?",
             "secenekler": ["A) 1903", "B) 1905", "C) 1907", "D) 1909"], "cevap": "C"},
            {"soru": "Galatasaray kaç yılında kurulmuştur?",
             "secenekler": ["A) 1899", "B) 1901", "C) 1903", "D) 1905"], "cevap": "D"},
            {"soru": "Beşiktaş kaç yılında kurulmuştur?",
             "secenekler": ["A) 1901", "B) 1903", "C) 1905", "D) 1907"], "cevap": "B"},
            {"soru": "2002 Dünya Kupası'nda Türkiye'nin teknik direktörü kimdi?",
             "secenekler": ["A) Fatih Terim", "B) Şenol Güneş", "C) Mustafa Denizli", "D) Lucescu"], "cevap": "B"},
            {"soru": "Şampiyonlar Ligi'nde en çok gol atan futbolcu kimdir?",
             "secenekler": ["A) Messi", "B) Cristiano Ronaldo", "C) Raul", "D) Lewandowski"], "cevap": "B"},
            {"soru": "Hangi futbolcu 'Egyptian King' lakabıyla bilinir?",
             "secenekler": ["A) Elneny", "B) Trezeguet", "C) Salah", "D) Hegazi"], "cevap": "C"},
            {"soru": "2018 Dünya Kupası'nı hangi ülke kazandı?",
             "secenekler": ["A) Hırvatistan", "B) Belçika", "C) Brezilya", "D) Fransa"], "cevap": "D"},
            {"soru": "Hangi futbolcu 'Flea' (Pire) lakabıyla bilinir?",
             "secenekler": ["A) Maradona", "B) Messi", "C) Neymar", "D) Ronaldinho"], "cevap": "B"},
            {"soru": "Premier Lig hangi yılda kurulmuştur?",
             "secenekler": ["A) 1888", "B) 1992", "C) 1960", "D) 2000"], "cevap": "B"},
            {"soru": "Manchester City'nin sahibi hangi ülkedendir?",
             "secenekler": ["A) Katar", "B) Suudi Arabistan", "C) BAE (Abu Dhabi)", "D) Bahreyn"], "cevap": "C"},
            {"soru": "PSG'nin sahibi hangi ülkedendir?",
             "secenekler": ["A) BAE", "B) Suudi Arabistan", "C) Katar", "D) Kuveyt"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'Il Trattore' (Traktör) lakabıyla bilinir?",
             "secenekler": ["A) Gattuso", "B) Vidal", "C) Kante", "D) Makelele"], "cevap": "A"},
            {"soru": "Ronaldo Nazario kaç Dünya Kupası golü atmıştır?",
             "secenekler": ["A) 10", "B) 12", "C) 15", "D) 18"], "cevap": "C"},
            {"soru": "Hangi ülke EURO 2024'e ev sahipliği yapmıştır?",
             "secenekler": ["A) İngiltere", "B) Almanya", "C) Fransa", "D) İspanya"], "cevap": "B"},
            {"soru": "EURO 2024'ü hangi ülke kazanmıştır?",
             "secenekler": ["A) İngiltere", "B) Fransa", "C) İspanya", "D) Almanya"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'Baby Shark' lakabıyla bilinir?",
             "secenekler": ["A) Vinicius", "B) Mbappe", "C) Lamine Yamal", "D) Saka"], "cevap": "C"},
            {"soru": "Galatasaray 2000 UEFA Kupası finalinde kimi yenmiştir?",
             "secenekler": ["A) Leeds United", "B) Arsenal", "C) Real Madrid", "D) Borussia Dortmund"], "cevap": "B"},
            {"soru": "Galatasaray 2000 UEFA Süper Kupa'da kimi yenmiştir?",
             "secenekler": ["A) Bayern Münih", "B) Real Madrid", "C) Milan", "D) Manchester United"], "cevap": "B"},
            {"soru": "Süper Lig'de en çok gol atan yabancı futbolcu kimdir?",
             "secenekler": ["A) Alex de Souza", "B) Hakan Şükür", "C) Samuel Eto'o", "D) Mario Gomez"], "cevap": "A"},
            {"soru": "Alex de Souza hangi takımda oynamıştır (Türkiye)?",
             "secenekler": ["A) Galatasaray", "B) Beşiktaş", "C) Fenerbahçe", "D) Trabzonspor"], "cevap": "C"},
            {"soru": "Trabzonspor ilk lig şampiyonluğunu hangi yıl kazandı?",
             "secenekler": ["A) 1975-76", "B) 1978-79", "C) 1980-81", "D) 2020-21"], "cevap": "A"},
            {"soru": "Trabzonspor en son ne zaman şampiyon olmuştur?",
             "secenekler": ["A) 2010-11", "B) 2019-20", "C) 2021-22", "D) 2023-24"], "cevap": "C"},
            {"soru": "Hangi Türk futbolcu Inter Milan'da oynamıştır?",
             "secenekler": ["A) Arda Turan", "B) Hakan Çalhanoğlu", "C) Emre Belözoğlu", "D) Nihat Kahveci"], "cevap": "B"},
            {"soru": "Hakan Çalhanoğlu hangi mevkide oynamaktadır?",
             "secenekler": ["A) Forvet", "B) Defans", "C) Orta saha", "D) Kaleci"], "cevap": "C"},
            {"soru": "Hangi Türk kaleci Premier Lig'de oynamıştır?",
             "secenekler": ["A) Volkan Demirel", "B) Uğurcan Çakır", "C) Altay Bayındır", "D) Fernando Muslera"], "cevap": "C"},
            {"soru": "Altay Bayındır hangi Premier Lig takımında oynamaktadır?",
             "secenekler": ["A) Arsenal", "B) Chelsea", "C) Manchester United", "D) Liverpool"], "cevap": "C"},
            {"soru": "Ferdi Kadıoğlu hangi kulüpte oynamaktadır (2024)?",
             "secenekler": ["A) Fenerbahçe", "B) Brighton", "C) PSV", "D) Galatasaray"], "cevap": "B"},
            {"soru": "Cenk Tosun en çok hangi Premier Lig takımında oynamıştır?",
             "secenekler": ["A) Liverpool", "B) Crystal Palace", "C) Everton", "D) West Ham"], "cevap": "C"},
            {"soru": "Arda Turan hangi İspanyol kulüplerinde oynamıştır?",
             "secenekler": ["A) Real Madrid-Sevilla", "B) Atletico Madrid-Barcelona", "C) Valencia-Villarreal", "D) Real Betis-Malaga"], "cevap": "B"},
            {"soru": "Nuri Şahin hangi Alman kulübünde oynamıştır?",
             "secenekler": ["A) Bayern Münih", "B) Schalke", "C) Borussia Dortmund", "D) Leverkusen"], "cevap": "C"},
            {"soru": "Mesut Özil hangi kulüplerde oynamıştır (büyük kulüpler)?",
             "secenekler": ["A) Dortmund-Barcelona", "B) Werder Bremen-Real Madrid-Arsenal", "C) Bayern-PSG", "D) Schalke-Juventus"], "cevap": "B"},
            {"soru": "İlkay Gündoğan hangi ülke milli takımında oynamaktadır?",
             "secenekler": ["A) Türkiye", "B) Almanya", "C) İngiltere", "D) İsviçre"], "cevap": "B"},
            {"soru": "Hangi Türk teknik direktör Leicester City'yi çalıştırmıştır?",
             "secenekler": ["A) Fatih Terim", "B) Şenol Güneş", "C) Okan Buruk", "D) Hiçbiri"], "cevap": "D"},
            {"soru": "Fatih Terim hangi İtalyan kulübünü çalıştırmıştır?",
             "secenekler": ["A) Roma", "B) Milan", "C) Fiorentina", "D) Inter"], "cevap": "C"},
            {"soru": "Fernando Muslera hangi ülkelidir?",
             "secenekler": ["A) Arjantin", "B) Paraguay", "C) Uruguay", "D) Brezilya"], "cevap": "C"},
            {"soru": "Okan Buruk hangi kulübün teknik direktörüdür (2024)?",
             "secenekler": ["A) Fenerbahçe", "B) Beşiktaş", "C) Galatasaray", "D) Trabzonspor"], "cevap": "C"},
            {"soru": "Jose Mourinho hangi Türk kulübünü çalıştırmıştır?",
             "secenekler": ["A) Galatasaray", "B) Beşiktaş", "C) Fenerbahçe", "D) Trabzonspor"], "cevap": "C"},
            {"soru": "Didier Deschamps hangi ülkenin milli takım teknik direktörüdür?",
             "secenekler": ["A) Belçika", "B) Fransa", "C) İtalya", "D) İspanya"], "cevap": "B"},
            {"soru": "Hangi futbolcu 'Jewel of Muscat' lakabıyla bilinir?",
             "secenekler": ["A) Salah", "B) Mahrez", "C) Ziyech", "D) Hakimi"], "cevap": "B"},
            {"soru": "Riyad Mahrez hangi ülkelidir?",
             "secenekler": ["A) Fas", "B) Tunus", "C) Cezayir", "D) Mısır"], "cevap": "C"},
            {"soru": "Victor Osimhen hangi ülkelidir?",
             "secenekler": ["A) Gana", "B) Kamerun", "C) Nijerya", "D) Senegal"], "cevap": "C"},
            {"soru": "Hangi futbolcu 2023 Afrika Kupası'nın en golcüsü olmuştur?",
             "secenekler": ["A) Salah", "B) Osimhen", "C) Lookman", "D) Mane"], "cevap": "C"},
            {"soru": "Copa America hangi kıtanın turnuvasıdır?",
             "secenekler": ["A) Avrupa", "B) Afrika", "C) Asya", "D) Güney Amerika"], "cevap": "D"},
            {"soru": "Afrika Uluslar Kupası (AFCON) kaç yılda bir yapılır?",
             "secenekler": ["A) Her yıl", "B) 2 yılda bir", "C) 3 yılda bir", "D) 4 yılda bir"], "cevap": "B"},
            {"soru": "Asya Kupası'nı en çok kazanan ülke hangisidir?",
             "secenekler": ["A) Güney Kore", "B) Japonya", "C) İran", "D) Suudi Arabistan"], "cevap": "B"},
            {"soru": "Concacaf hangi bölgenin futbol federasyonudur?",
             "secenekler": ["A) Güney Amerika", "B) Kuzey/Orta Amerika ve Karayipler", "C) Afrika", "D) Asya"], "cevap": "B"},
            {"soru": "Libertadores Kupası hangi kıtanın kulüp turnuvasıdır?",
             "secenekler": ["A) Avrupa", "B) Afrika", "C) Güney Amerika", "D) Asya"], "cevap": "C"},
            {"soru": "FIFA Kulüpler Dünya Kupası'nı en çok kazanan takım hangisidir?",
             "secenekler": ["A) Barcelona", "B) Real Madrid", "C) Milan", "D) Bayern Münih"], "cevap": "B"},
            {"soru": "Avrupa Ligi'ni (UEFA Cup/Europa League) en çok kazanan takım hangisidir?",
             "secenekler": ["A) Atletico Madrid", "B) Sevilla", "C) Inter", "D) Juventus"], "cevap": "B"},
            {"soru": "Conference League hangi yıl başlamıştır?",
             "secenekler": ["A) 2019-20", "B) 2020-21", "C) 2021-22", "D) 2022-23"], "cevap": "C"},
        ],
        "orta": [
            {"soru": "Şampiyonlar Ligi'ni en çok kazanan takım hangisidir?",
             "secenekler": ["A) Barcelona", "B) Bayern Münih", "C) Real Madrid", "D) Milan"], "cevap": "C"},
            {"soru": "Cristiano Ronaldo hangi ülkelidir?",
             "secenekler": ["A) İspanya", "B) Brezilya", "C) Portekiz", "D) Arjantin"], "cevap": "C"},
            {"soru": "Lionel Messi hangi ülkelidir?",
             "secenekler": ["A) Brezilya", "B) Arjantin", "C) Uruguay", "D) İspanya"], "cevap": "B"},
            {"soru": "Premier Lig hangi ülkenin ligidir?",
             "secenekler": ["A) Almanya", "B) İngiltere", "C) Fransa", "D) İtalya"], "cevap": "B"},
            {"soru": "La Liga hangi ülkenin ligidir?",
             "secenekler": ["A) İtalya", "B) Fransa", "C) İspanya", "D) Almanya"], "cevap": "C"},
            {"soru": "Serie A hangi ülkenin ligidir?",
             "secenekler": ["A) İspanya", "B) İtalya", "C) Fransa", "D) Portekiz"], "cevap": "B"},
            {"soru": "Bundesliga hangi ülkenin ligidir?",
             "secenekler": ["A) Avusturya", "B) İsviçre", "C) Almanya", "D) Hollanda"], "cevap": "C"},
            {"soru": "Hat-trick ne demektir?",
             "secenekler": ["A) 2 gol", "B) 3 gol", "C) 4 gol", "D) 5 gol"], "cevap": "B"},
            {"soru": "Neymar hangi ülke milli takımında oynar?",
             "secenekler": ["A) Arjantin", "B) Kolombiya", "C) Brezilya", "D) Portekiz"], "cevap": "C"},
            {"soru": "Ballon d'Or ödülü neyi temsil eder?",
             "secenekler": ["A) En iyi takım", "B) En iyi kaleci", "C) Yılın en iyi oyuncusu", "D) En çok gol"], "cevap": "C"},
            {"soru": "2014 Dünya Kupası finalinde hangi takım kazandı?",
             "secenekler": ["A) Brezilya", "B) Arjantin", "C) Hollanda", "D) Almanya"], "cevap": "D"},
            {"soru": "Galatasaray UEFA Kupasını hangi yıl kazandı?",
             "secenekler": ["A) 1998", "B) 1999", "C) 2000", "D) 2001"], "cevap": "C"},
            {"soru": "Erling Haaland hangi ülkelidir?",
             "secenekler": ["A) İsveç", "B) Danimarka", "C) Norveç", "D) Finlandiya"], "cevap": "C"},
            {"soru": "Kylian Mbappe hangi ülkelidir?",
             "secenekler": ["A) Belçika", "B) Fransa", "C) İspanya", "D) Portekiz"], "cevap": "B"},
            {"soru": "VAR sistemi ne işe yarar?",
             "secenekler": ["A) Skor takibi", "B) Video ile pozisyon inceleme", "C) Oyuncu takibi", "D) Saha bakımı"], "cevap": "B"},
            {"soru": "2010 Dünya Kupası nerede yapıldı?",
             "secenekler": ["A) Almanya", "B) Brezilya", "C) Güney Afrika", "D) Rusya"], "cevap": "C"},
            {"soru": "Maradona hangi ülkelidir?",
             "secenekler": ["A) Brezilya", "B) Arjantin", "C) Uruguay", "D) İtalya"], "cevap": "B"},
            {"soru": "Türkiye 2002 Dünya Kupasında kaçıncı oldu?",
             "secenekler": ["A) 1.", "B) 2.", "C) 3.", "D) 4."], "cevap": "C"},
            {"soru": "2022 Dünya Kupasını hangi ülke kazandı?",
             "secenekler": ["A) Fransa", "B) Brezilya", "C) Arjantin", "D) Hırvatistan"], "cevap": "C"},
            {"soru": "Mohamed Salah hangi ülkelidir?",
             "secenekler": ["A) Tunus", "B) Cezayir", "C) Fas", "D) Mısır"], "cevap": "D"},
            {"soru": "Robert Lewandowski hangi ülkelidir?",
             "secenekler": ["A) Almanya", "B) Çekya", "C) Polonya", "D) Hırvatistan"], "cevap": "C"},
            {"soru": "Luka Modric hangi ülkelidir?",
             "secenekler": ["A) Sırbistan", "B) Hırvatistan", "C) Bosna", "D) Slovenya"], "cevap": "B"},
            {"soru": "Barcelona hangi ülkenin takımıdır?",
             "secenekler": ["A) Portekiz", "B) İspanya", "C) İtalya", "D) Fransa"], "cevap": "B"},
            {"soru": "Manchester United hangi şehrin takımıdır?",
             "secenekler": ["A) Londra", "B) Liverpool", "C) Manchester", "D) Birmingham"], "cevap": "C"},
            {"soru": "Fenerbahçe'nin renkleri nedir?",
             "secenekler": ["A) Kırmızı-Sarı", "B) Siyah-Beyaz", "C) Sarı-Lacivert", "D) Bordo-Mavi"], "cevap": "C"},
            {"soru": "Beşiktaş'ın renkleri nedir?",
             "secenekler": ["A) Kırmızı-Beyaz", "B) Siyah-Beyaz", "C) Sarı-Kırmızı", "D) Mavi-Beyaz"], "cevap": "B"},
            {"soru": "Galatasaray'ın renkleri nedir?",
             "secenekler": ["A) Sarı-Kırmızı", "B) Siyah-Beyaz", "C) Sarı-Lacivert", "D) Bordo-Mavi"], "cevap": "A"},
            {"soru": "2018 Dünya Kupası nerede yapıldı?",
             "secenekler": ["A) Brezilya", "B) Rusya", "C) Katar", "D) Güney Afrika"], "cevap": "B"},
            {"soru": "Ligue 1 hangi ülkenin ligidir?",
             "secenekler": ["A) Belçika", "B) İsviçre", "C) Fransa", "D) Hollanda"], "cevap": "C"},
            {"soru": "Kevin De Bruyne hangi ülkelidir?",
             "secenekler": ["A) Hollanda", "B) Fransa", "C) Belçika", "D) Almanya"], "cevap": "C"},
            {"soru": "Virgil van Dijk hangi ülkelidir?",
             "secenekler": ["A) Belçika", "B) Hollanda", "C) Almanya", "D) Danimarka"], "cevap": "B"},
            {"soru": "Haaland hangi kulüpte oynamaktadır (2024)?",
             "secenekler": ["A) Real Madrid", "B) Manchester City", "C) PSG", "D) Bayern Münih"], "cevap": "B"},
            {"soru": "Mbappe 2024'te hangi kulübe transfer oldu?",
             "secenekler": ["A) Manchester United", "B) Barcelona", "C) Real Madrid", "D) Bayern Münih"], "cevap": "C"},
            {"soru": "Avrupa Şampiyonası (EURO) kaç yılda bir yapılır?",
             "secenekler": ["A) 2", "B) 3", "C) 4", "D) 5"], "cevap": "C"},
            {"soru": "2020 EURO finalinde hangi takım kazandı?",
             "secenekler": ["A) İngiltere", "B) İtalya", "C) İspanya", "D) Danimarka"], "cevap": "B"},
            {"soru": "Sadio Mane hangi ülkelidir?",
             "secenekler": ["A) Gana", "B) Senegal", "C) Nijerya", "D) Fildişi Sahili"], "cevap": "B"},
            {"soru": "Jude Bellingham hangi ülkelidir?",
             "secenekler": ["A) ABD", "B) Fransa", "C) İngiltere", "D) Almanya"], "cevap": "C"},
            {"soru": "Vinicius Junior hangi ülkelidir?",
             "secenekler": ["A) Arjantin", "B) Kolombiya", "C) Brezilya", "D) Portekiz"], "cevap": "C"},
            {"soru": "Pedri hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Real Madrid", "B) Barcelona", "C) Atletico Madrid", "D) Sevilla"], "cevap": "B"},
            {"soru": "Thibaut Courtois hangi mevkide oynar?",
             "secenekler": ["A) Forvet", "B) Defans", "C) Orta saha", "D) Kaleci"], "cevap": "D"},
            {"soru": "Süper Lig'de bir sezon kaç takım mücadele eder (2024)?",
             "secenekler": ["A) 16", "B) 18", "C) 19", "D) 20"], "cevap": "C"},
            {"soru": "Icardi hangi ülkelidir?",
             "secenekler": ["A) Brezilya", "B) Arjantin", "C) Uruguay", "D) Kolombiya"], "cevap": "B"},
            {"soru": "Arda Güler hangi kulüpte oynamaktadır (2024)?",
             "secenekler": ["A) Fenerbahçe", "B) Barcelona", "C) Real Madrid", "D) Bayern Münih"], "cevap": "C"},
            {"soru": "Trabzonspor'un renkleri nedir?",
             "secenekler": ["A) Sarı-Kırmızı", "B) Bordo-Mavi", "C) Siyah-Beyaz", "D) Yeşil-Beyaz"], "cevap": "B"},
            {"soru": "Son Heung-min hangi ülkelidir?",
             "secenekler": ["A) Japonya", "B) Çin", "C) Güney Kore", "D) Tayland"], "cevap": "C"},
            {"soru": "Bukayo Saka hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Chelsea", "B) Arsenal", "C) Tottenham", "D) Liverpool"], "cevap": "B"},
            {"soru": "Phil Foden hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Liverpool", "B) Chelsea", "C) Manchester City", "D) Arsenal"], "cevap": "C"},
            {"soru": "Florian Wirtz hangi ülkelidir?",
             "secenekler": ["A) Avusturya", "B) İsviçre", "C) Almanya", "D) Hollanda"], "cevap": "C"},
            {"soru": "Lamine Yamal hangi kulüpte oynamaktadır (2024)?",
             "secenekler": ["A) Real Madrid", "B) Barcelona", "C) Atletico Madrid", "D) PSG"], "cevap": "B"},
            {"soru": "Rodri hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Barcelona", "B) Real Madrid", "C) Manchester City", "D) Bayern Münih"], "cevap": "C"},
            {"soru": "2024 Ballon d'Or ödülünü kim kazandı?",
             "secenekler": ["A) Messi", "B) Haaland", "C) Vinicius", "D) Rodri"], "cevap": "D"},
            {"soru": "Declan Rice hangi kulüpte oynamaktadır (2024)?",
             "secenekler": ["A) West Ham", "B) Arsenal", "C) Chelsea", "D) Man City"], "cevap": "B"},
            {"soru": "Jamal Musiala hangi ülkelidir?",
             "secenekler": ["A) İngiltere", "B) Almanya", "C) Fransa", "D) İspanya"], "cevap": "B"},
            {"soru": "Gavi hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Real Madrid", "B) Sevilla", "C) Barcelona", "D) Atletico"], "cevap": "C"},
            {"soru": "Marcus Rashford hangi kulüpte oynamaktadır?",
             "secenekler": ["A) Liverpool", "B) Man City", "C) Man United", "D) Chelsea"], "cevap": "C"},
            {"soru": "Federico Valverde hangi ülkelidir?",
             "secenekler": ["A) Arjantin", "B) Paraguay", "C) Uruguay", "D) Şili"], "cevap": "C"},
            {"soru": "Alphonso Davies hangi ülkelidir?",
             "secenekler": ["A) ABD", "B) Kanada", "C) Jamaika", "D) Meksika"], "cevap": "B"},
            {"soru": "Juventus'un lakabı nedir?",
             "secenekler": ["A) Rossoneri", "B) Nerazzurri", "C) Bianconeri", "D) Giallorossi"], "cevap": "C"},
            {"soru": "Milan'ın lakabı nedir?",
             "secenekler": ["A) Nerazzurri", "B) Rossoneri", "C) Bianconeri", "D) Azzurri"], "cevap": "B"},
            {"soru": "Inter Milan'ın lakabı nedir?",
             "secenekler": ["A) Rossoneri", "B) Bianconeri", "C) Nerazzurri", "D) Partenopei"], "cevap": "C"},
        ],
        "zor": [
            {"soru": "Zidane 2006 finalinde kime kafa attı?",
             "secenekler": ["A) Pirlo", "B) Materazzi", "C) Buffon", "D) Gattuso"], "cevap": "B"},
            {"soru": "İlk Dünya Kupası hangi ülkede düzenlendi?",
             "secenekler": ["A) Brezilya", "B) Fransa", "C) Uruguay", "D) İtalya"], "cevap": "C"},
            {"soru": "'The Invincibles' hangi takımdır?",
             "secenekler": ["A) Arsenal", "B) Chelsea", "C) Liverpool", "D) Man United"], "cevap": "A"},
            {"soru": "Bosman kuralı hangi yıl yürürlüğe girdi?",
             "secenekler": ["A) 1993", "B) 1995", "C) 1998", "D) 2000"], "cevap": "B"},
            {"soru": "En fazla Dünya Kupası kazanan ülke hangisidir?",
             "secenekler": ["A) Almanya", "B) İtalya", "C) Arjantin", "D) Brezilya"], "cevap": "D"},
            {"soru": "2005 Şampiyonlar Ligi finalinde Liverpool kaç gol geriden geldi?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 4"], "cevap": "C"},
            {"soru": "'O Fenomeno' lakabı kime aittir?",
             "secenekler": ["A) Ronaldinho", "B) Ronaldo Nazario", "C) Rivaldo", "D) Romario"], "cevap": "B"},
            {"soru": "Hangi kaleci 'Kara Örümcek' olarak bilinir?",
             "secenekler": ["A) Banks", "B) Yashin", "C) Zoff", "D) Schmeichel"], "cevap": "B"},
            {"soru": "Maradona'nın 'Tanrının Eli' golü hangi Dünya Kupasında atıldı?",
             "secenekler": ["A) 1982", "B) 1986", "C) 1990", "D) 1994"], "cevap": "B"},
            {"soru": "Hangi takım 'Galacticos' olarak bilinir?",
             "secenekler": ["A) Barcelona", "B) Milan", "C) Real Madrid", "D) PSG"], "cevap": "C"},
            {"soru": "İtalya milli takımının lakabı nedir?",
             "secenekler": ["A) La Roja", "B) Les Bleus", "C) Azzurri", "D) Selecao"], "cevap": "C"},
            {"soru": "Brezilya milli takımının lakabı nedir?",
             "secenekler": ["A) Azzurri", "B) Selecao", "C) La Roja", "D) Oranje"], "cevap": "B"},
            {"soru": "En çok Süper Lig şampiyonluğu kazanan takım hangisidir?",
             "secenekler": ["A) Fenerbahçe", "B) Beşiktaş", "C) Galatasaray", "D) Trabzonspor"], "cevap": "C"},
            {"soru": "Puskas Ödülü neye verilir?",
             "secenekler": ["A) En iyi kaleci", "B) Yılın en güzel golü", "C) En iyi defans", "D) Fair play"], "cevap": "B"},
            {"soru": "1998 Dünya Kupasını hangi ülke kazandı?",
             "secenekler": ["A) Brezilya", "B) İtalya", "C) Almanya", "D) Fransa"], "cevap": "D"},
            {"soru": "1994 Dünya Kupası finalinde penaltı kaçıran İtalyan kim?",
             "secenekler": ["A) Baggio", "B) Baresi", "C) Maldini", "D) Del Piero"], "cevap": "A"},
            {"soru": "Pele kaç Dünya Kupası kazanmıştır?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 4"], "cevap": "C"},
            {"soru": "2006 Dünya Kupasını hangi ülke kazandı?",
             "secenekler": ["A) Fransa", "B) Almanya", "C) İtalya", "D) Brezilya"], "cevap": "C"},
            {"soru": "Catenaccio futbol anlayışı hangi ülkeye aittir?",
             "secenekler": ["A) Almanya", "B) Hollanda", "C) İtalya", "D) İngiltere"], "cevap": "C"},
            {"soru": "Zinedine Zidane hangi ülkelidir?",
             "secenekler": ["A) İtalya", "B) İspanya", "C) Cezayir", "D) Fransa"], "cevap": "D"},
            {"soru": "Hangi stadyum 'Futbolun Katedrali' olarak bilinir?",
             "secenekler": ["A) Camp Nou", "B) Wembley", "C) San Siro", "D) Maracana"], "cevap": "B"},
            {"soru": "Ajax'ın efsanevi antrenörü kimdir?",
             "secenekler": ["A) Cruyff", "B) Van Basten", "C) Michels", "D) Rijkaard"], "cevap": "C"},
            {"soru": "Bayern Münih hangi şehrin takımıdır?",
             "secenekler": ["A) Berlin", "B) Hamburg", "C) Münih", "D) Dortmund"], "cevap": "C"},
            {"soru": "İngiltere milli takımının lakabı nedir?",
             "secenekler": ["A) Three Lions", "B) Les Bleus", "C) La Roja", "D) Die Mannschaft"], "cevap": "A"},
            {"soru": "Almanya milli takımının lakabı nedir?",
             "secenekler": ["A) Three Lions", "B) Azzurri", "C) Die Mannschaft", "D) Oranje"], "cevap": "C"},
            {"soru": "Hollanda milli takımının lakabı nedir?",
             "secenekler": ["A) La Roja", "B) Oranje", "C) Selecao", "D) Three Lions"], "cevap": "B"},
            {"soru": "İspanya milli takımının lakabı nedir?",
             "secenekler": ["A) Les Bleus", "B) Selecao", "C) La Roja", "D) Azzurri"], "cevap": "C"},
            {"soru": "Fransa milli takımının lakabı nedir?",
             "secenekler": ["A) Les Bleus", "B) La Roja", "C) Oranje", "D) Three Lions"], "cevap": "A"},
            {"soru": "Hangi futbolcu 'Kral' lakabıyla bilinir (Türkiye)?",
             "secenekler": ["A) Hakan Şükür", "B) Metin Oktay", "C) Lefter", "D) Rüştü Reçber"], "cevap": "B"},
            {"soru": "2002 Dünya Kupasında en hızlı golü kim attı?",
             "secenekler": ["A) Ronaldo", "B) Rivaldo", "C) Hakan Şükür", "D) Klose"], "cevap": "C"},
            {"soru": "Camp Nou hangi takımın stadyumudur?",
             "secenekler": ["A) Real Madrid", "B) Barcelona", "C) Atletico Madrid", "D) Valencia"], "cevap": "B"},
            {"soru": "Santiago Bernabeu hangi takımın stadyumudur?",
             "secenekler": ["A) Barcelona", "B) Atletico Madrid", "C) Real Madrid", "D) Sevilla"], "cevap": "C"},
            {"soru": "Old Trafford hangi takımın stadyumudur?",
             "secenekler": ["A) Liverpool", "B) Man City", "C) Arsenal", "D) Man United"], "cevap": "D"},
            {"soru": "Anfield hangi takımın stadyumudur?",
             "secenekler": ["A) Everton", "B) Liverpool", "C) Man United", "D) Chelsea"], "cevap": "B"},
            {"soru": "Signal Iduna Park hangi takımın stadyumudur?",
             "secenekler": ["A) Bayern Münih", "B) Schalke", "C) Borussia Dortmund", "D) Leipzig"], "cevap": "C"},
            {"soru": "San Siro stadyumu hangi şehirdedir?",
             "secenekler": ["A) Roma", "B) Torino", "C) Napoli", "D) Milano"], "cevap": "D"},
            {"soru": "Maracana stadyumu hangi şehirdedir?",
             "secenekler": ["A) Sao Paulo", "B) Buenos Aires", "C) Rio de Janeiro", "D) Lima"], "cevap": "C"},
            {"soru": "Thierry Henry hangi takımın efsanesidir?",
             "secenekler": ["A) Chelsea", "B) Arsenal", "C) Liverpool", "D) Tottenham"], "cevap": "B"},
            {"soru": "Paolo Maldini hangi takımda oynadı?",
             "secenekler": ["A) Juventus", "B) Inter", "C) Milan", "D) Roma"], "cevap": "C"},
            {"soru": "Xavi Hernandez hangi takımın efsanesidir?",
             "secenekler": ["A) Real Madrid", "B) Barcelona", "C) Atletico", "D) Valencia"], "cevap": "B"},
            {"soru": "Andrea Pirlo hangi mevkide oynardı?",
             "secenekler": ["A) Defans", "B) Orta saha", "C) Forvet", "D) Kaleci"], "cevap": "B"},
            {"soru": "Premier Lig'de en çok gol atan futbolcu kimdir?",
             "secenekler": ["A) Wayne Rooney", "B) Alan Shearer", "C) Thierry Henry", "D) Andrew Cole"], "cevap": "B"},
            {"soru": "2019-20 Şampiyonlar Ligi'ni hangi takım kazandı?",
             "secenekler": ["A) PSG", "B) Bayern Münih", "C) Liverpool", "D) Real Madrid"], "cevap": "B"},
            {"soru": "Hangi futbolcu 'Kara Panter' lakabıyla bilinir?",
             "secenekler": ["A) Drogba", "B) Eto'o", "C) Eusebio", "D) Weah"], "cevap": "C"},
            {"soru": "Lev Yashin hangi mevkide oynardı?",
             "secenekler": ["A) Forvet", "B) Defans", "C) Orta saha", "D) Kaleci"], "cevap": "D"},
            {"soru": "Hangi takım 'Sarı Duvar' (Gelbe Wand) ile ünlüdür?",
             "secenekler": ["A) Bayern Münih", "B) Borussia Dortmund", "C) Schalke", "D) Leipzig"], "cevap": "B"},
            {"soru": "George Best hangi ülkelidir?",
             "secenekler": ["A) İngiltere", "B) İskoçya", "C) Kuzey İrlanda", "D) Galler"], "cevap": "C"},
            {"soru": "Ronaldinho kaç kez Ballon d'Or kazanmıştır?",
             "secenekler": ["A) 0", "B) 1", "C) 2", "D) 3"], "cevap": "B"},
            {"soru": "Hangi ülke hiç Dünya Kupası'na katılmamıştır?",
             "secenekler": ["A) İzlanda", "B) Hindistan", "C) Panama", "D) Hepsi katılmıştır"], "cevap": "B"},
            {"soru": "2023 Şampiyonlar Ligi'ni hangi takım kazandı?",
             "secenekler": ["A) Inter", "B) Manchester City", "C) Real Madrid", "D) Bayern Münih"], "cevap": "B"},
        ],
        "cok_zor": [
            {"soru": "Johan Cruyff hangi futbol felsefesiyle özdeşleşmiştir?",
             "secenekler": ["A) Catenaccio", "B) Total Football", "C) Gegenpressing", "D) Libero"], "cevap": "B"},
            {"soru": "Pele'nin iddia ettiği toplam gol sayısı kaçtır?",
             "secenekler": ["A) 1180", "B) 1201", "C) 1281", "D) 1305"], "cevap": "C"},
            {"soru": "İlk Dünya Kupası finalini hangi ülke kazandı?",
             "secenekler": ["A) Arjantin", "B) Brezilya", "C) Uruguay", "D) İtalya"], "cevap": "C"},
            {"soru": "Arrigo Sacchi hangi takımda devrim yapmıştır?",
             "secenekler": ["A) Juventus", "B) Inter", "C) Milan", "D) Roma"], "cevap": "C"},
            {"soru": "Hangi oyuncu 'Der Kaiser' lakabıyla bilinir?",
             "secenekler": ["A) Müller", "B) Beckenbauer", "C) Rummenigge", "D) Matthaus"], "cevap": "B"},
            {"soru": "1950 Dünya Kupası finalinde Uruguay hangi takımı yenmiştir?",
             "secenekler": ["A) İtalya", "B) İsveç", "C) Brezilya", "D) Arjantin"], "cevap": "C"},
            {"soru": "Hangi takım İtalya'da 'La Vecchia Signora' olarak bilinir?",
             "secenekler": ["A) Milan", "B) Inter", "C) Roma", "D) Juventus"], "cevap": "D"},
            {"soru": "Eusebio hangi ülkenin futbolcusudur?",
             "secenekler": ["A) Brezilya", "B) Mozambik/Portekiz", "C) Angola", "D) İspanya"], "cevap": "B"},
            {"soru": "Hangi Dünya Kupasında ilk kez VAR kullanılmıştır?",
             "secenekler": ["A) 2014", "B) 2018", "C) 2022", "D) 2010"], "cevap": "B"},
            {"soru": "Wunderteam hangi ülkenin takımıydı?",
             "secenekler": ["A) Almanya", "B) Macaristan", "C) Avusturya", "D) Çekoslovakya"], "cevap": "C"},
            {"soru": "Heysel faciası hangi yılda yaşandı?",
             "secenekler": ["A) 1982", "B) 1985", "C) 1989", "D) 1992"], "cevap": "B"},
            {"soru": "Hillsborough faciası hangi yılda yaşandı?",
             "secenekler": ["A) 1985", "B) 1987", "C) 1989", "D) 1991"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'Il Divin Codino' lakabıyla bilinir?",
             "secenekler": ["A) Pirlo", "B) Del Piero", "C) Baggio", "D) Totti"], "cevap": "C"},
            {"soru": "Hangi antrenör 'The Special One' lakabıyla bilinir?",
             "secenekler": ["A) Guardiola", "B) Mourinho", "C) Klopp", "D) Ancelotti"], "cevap": "B"},
            {"soru": "Tiki-taka futbol anlayışı en çok hangi takımla özdeşleşmiştir?",
             "secenekler": ["A) Real Madrid", "B) Barcelona", "C) Bayern Münih", "D) Juventus"], "cevap": "B"},
            {"soru": "Gegenpressing futbol anlayışını popüler yapan antrenör kimdir?",
             "secenekler": ["A) Guardiola", "B) Ancelotti", "C) Klopp", "D) Mourinho"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'La Pulga' (Pire) lakabıyla bilinir?",
             "secenekler": ["A) Ronaldo", "B) Neymar", "C) Messi", "D) Maradona"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'CR7' koduyla bilinir?",
             "secenekler": ["A) Cruyff", "B) Carlos Roberto", "C) Cristiano Ronaldo", "D) Cafu"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'El Pibe de Oro' lakabıyla bilinir?",
             "secenekler": ["A) Pele", "B) Maradona", "C) Messi", "D) Di Stefano"], "cevap": "B"},
            {"soru": "Avrupa'da ilk UEFA kupasını kazanan Türk takımı hangisidir?",
             "secenekler": ["A) Beşiktaş", "B) Fenerbahçe", "C) Trabzonspor", "D) Galatasaray"], "cevap": "D"},
            {"soru": "Di Stefano hangi iki milli takımda oynamıştır?",
             "secenekler": ["A) Brezilya-Portekiz", "B) Arjantin-İspanya", "C) Uruguay-İtalya", "D) Kolombiya-Arjantin"], "cevap": "B"},
            {"soru": "Hangi futbolcu Ballon d'Or'u en çok kazanmıştır?",
             "secenekler": ["A) Ronaldo", "B) Cruyff", "C) Messi", "D) Pele"], "cevap": "C"},
            {"soru": "1954 Dünya Kupası finalinde sürpriz yapan takım hangisidir?",
             "secenekler": ["A) Uruguay", "B) Batı Almanya", "C) Macaristan", "D) İsveç"], "cevap": "B"},
            {"soru": "Macaristan'ın 1950'lerdeki efsanevi takımının lakabı nedir?",
             "secenekler": ["A) Sihirli Macarlar", "B) Altın Takım", "C) Aranycsapat", "D) Hepsi doğru"], "cevap": "D"},
            {"soru": "Hangi kulüp 'Millonarios' lakabıyla da bilinir (Arjantin)?",
             "secenekler": ["A) Boca Juniors", "B) Racing", "C) River Plate", "D) Independiente"], "cevap": "C"},
            {"soru": "1958 Dünya Kupası'nda en genç golcü kimdi?",
             "secenekler": ["A) Garrincha", "B) Pele", "C) Didi", "D) Vava"], "cevap": "B"},
            {"soru": "Hangi takım 'Busby Babes' olarak bilinirdi?",
             "secenekler": ["A) Liverpool", "B) Arsenal", "C) Man United", "D) Tottenham"], "cevap": "C"},
            {"soru": "Münih hava faciası hangi yılda yaşandı?",
             "secenekler": ["A) 1956", "B) 1958", "C) 1960", "D) 1962"], "cevap": "B"},
            {"soru": "Superga faciası hangi takımı etkilemiştir?",
             "secenekler": ["A) Milan", "B) Juventus", "C) Torino", "D) Inter"], "cevap": "C"},
            {"soru": "Hangi futbolcu 'Galloping Major' lakabıyla bilinir?",
             "secenekler": ["A) Di Stefano", "B) Puskas", "C) Kocsis", "D) Hidegkuti"], "cevap": "B"},
            {"soru": "İlk altın gol kuralıyla biten Dünya Kupası maçı hangisidir?",
             "secenekler": ["A) 1998 Fransa-Paraguay", "B) 2002 Senegal-İsveç", "C) 1998 Fransa-İtalya", "D) 2002 Güney Kore-İtalya"], "cevap": "A"},
            {"soru": "Hangi futbolcu 'Il Fenomeno' ve 'R9' olarak da bilinir?",
             "secenekler": ["A) Rivaldo", "B) Ronaldo Nazario", "C) Ronaldinho", "D) Romario"], "cevap": "B"},
            {"soru": "Ferenc Puskas hangi ülkelidir?",
             "secenekler": ["A) Çekoslovakya", "B) Yugoslavya", "C) Macaristan", "D) Romanya"], "cevap": "C"},
            {"soru": "Hangi antrenör 'Taktik Deha' lakabıyla bilinir?",
             "secenekler": ["A) Sacchi", "B) Capello", "C) Lippi", "D) Bielsa"], "cevap": "D"},
            {"soru": "Dünya Kupası tarihinde en çok gol atan futbolcu kimdir?",
             "secenekler": ["A) Pele", "B) Ronaldo", "C) Miroslav Klose", "D) Gerd Müller"], "cevap": "C"},
            {"soru": "Hangi ülke art arda iki Dünya Kupası kazanan son takımdır?",
             "secenekler": ["A) İtalya", "B) Brezilya", "C) Almanya", "D) Arjantin"], "cevap": "B"},
            {"soru": "Calciopoli skandalı hangi yılda patlamıştır?",
             "secenekler": ["A) 2004", "B) 2006", "C) 2008", "D) 2010"], "cevap": "B"},
            {"soru": "Hangi takım Calciopoli nedeniyle küme düşürülmüştür?",
             "secenekler": ["A) Milan", "B) Inter", "C) Juventus", "D) Roma"], "cevap": "C"},
            {"soru": "Libero pozisyonunu popüler yapan futbolcu kimdir?",
             "secenekler": ["A) Maldini", "B) Beckenbauer", "C) Baresi", "D) Nesta"], "cevap": "B"},
            {"soru": "Hangi Dünya Kupası'nda 'Jogo Bonito' (Güzel Oyun) kavramı doğmuştur?",
             "secenekler": ["A) 1954", "B) 1958", "C) 1962", "D) 1970"], "cevap": "D"},
             {"soru": "Hangi takım İngiltere'de ilk 'Double' (lig+kupa) yapan takımdır?",
             "secenekler": ["A) Man United", "B) Liverpool", "C) Preston North End", "D) Aston Villa"], "cevap": "C"},
            {"soru": "Hangi futbolcu tek bir Dünya Kupası'nda 13 gol atmıştır?",
             "secenekler": ["A) Pele", "B) Fontaine", "C) Müller", "D) Kocsis"], "cevap": "B"},
            {"soru": "1930 Dünya Kupası finalinde kaç takım katılmıştır?",
             "secenekler": ["A) 8", "B) 13", "C) 16", "D) 24"], "cevap": "B"},
            {"soru": "Hangi antrenör 'Il Mister' olarak bilinir (İtalya)?",
             "secenekler": ["A) Lippi", "B) Capello", "C) Sacchi", "D) Herrera"], "cevap": "D"},
            {"soru": "WM formasyonunu kim geliştirmiştir?",
             "secenekler": ["A) Michels", "B) Chapman", "C) Sacchi", "D) Cruyff"], "cevap": "B"},
            {"soru": "Hangi ülke 1950 Dünya Kupası'nda İngiltere'yi yenerek sürpriz yapmıştır?",
             "secenekler": ["A) İrlanda", "B) ABD", "C) Portekiz", "D) İsveç"], "cevap": "B"},
            {"soru": "Garrincha'nın lakabı nedir?",
             "secenekler": ["A) O Rei", "B) Alegria do Povo", "C) O Fenomeno", "D) Canhotinha de Ouro"], "cevap": "B"},
            {"soru": "Hangi futbolcu 'Der Bomber' lakabıyla bilinir?",
             "secenekler": ["A) Beckenbauer", "B) Matthäus", "C) Gerd Müller", "D) Rummenigge"], "cevap": "C"},
            {"soru": "1982 Dünya Kupası yarı finalinde Almanya-Fransa maçı neden ünlüdür?",
             "secenekler": ["A) Schumacher'in Battiston'a müdahalesi", "B) 10 gol atıldı", "C) Hakem hatası", "D) Saha istilası"], "cevap": "A"},
            {"soru": "Hangi futbolcu 'The Black Pearl' lakabıyla bilinir?",
             "secenekler": ["A) Pele", "B) Eusebio", "C) Drogba", "D) Weah"], "cevap": "B"},
            {"soru": "1974 Dünya Kupası'nda 'Total Football' hangi takımla özdeşleşmiştir?",
             "secenekler": ["A) Brezilya", "B) Almanya", "C) Hollanda", "D) İtalya"], "cevap": "C"},
            {"soru": "Hangi kural 1992'de geri pas kuralı olarak değiştirilmiştir?",
             "secenekler": ["A) Ofsayt", "B) Kalecinin geri pası elle alması yasaklandı", "C) Penaltı mesafesi", "D) Kırmızı kart kuralı"], "cevap": "B"},
            {"soru": "Alfredo Di Stefano kaç Şampiyonlar Ligi kazanmıştır?",
             "secenekler": ["A) 3", "B) 4", "C) 5", "D) 6"], "cevap": "C"},
            {"soru": "FIFA'nın kuruluş yılı nedir?",
             "secenekler": ["A) 1900", "B) 1904", "C) 1910", "D) 1920"], "cevap": "B"},
            {"soru": "İlk resmi uluslararası futbol maçı hangi iki ülke arasında oynandı?",
             "secenekler": ["A) İngiltere-Fransa", "B) İngiltere-İskoçya", "C) İngiltere-Galler", "D) Almanya-Avusturya"], "cevap": "B"},
            {"soru": "Hangi ülke 2030 Dünya Kupası'nın ana ev sahibi olacak?",
             "secenekler": ["A) İspanya-Portekiz-Fas", "B) İngiltere", "C) Suudi Arabistan", "D) Arjantin"], "cevap": "A"},
            {"soru": "Hangi futbolcu 'Pipita' lakabıyla bilinir?",
             "secenekler": ["A) Tevez", "B) Higuain", "C) Aguero", "D) Di Maria"], "cevap": "B"},
            {"soru": "Hangi antrenör 'Don' lakabıyla bilinir?",
             "secenekler": ["A) Sacchi", "B) Lippi", "C) Ancelotti", "D) Revie"], "cevap": "D"},
            {"soru": "Hangi futbolcu 'Joga Bonito'nun sembolüdür?",
             "secenekler": ["A) Pele", "B) Ronaldinho", "C) Neymar", "D) Garrincha"], "cevap": "B"},
            {"soru": "Brian Clough hangi iki takımla Şampiyonlar Ligi kazanmıştır?",
             "secenekler": ["A) Liverpool", "B) Hiçbiri, Nottingham Forest ile 2 kez", "C) Man United", "D) Leeds"], "cevap": "B"},
            {"soru": "Hangi futbolcu bir Dünya Kupası maçında 5 gol atmıştır (tek maç)?",
             "secenekler": ["A) Pele", "B) Klose", "C) Salenko", "D) Eusebio"], "cevap": "C"},
            {"soru": "İlk Ballon d'Or ödülünü kim kazanmıştır?",
             "secenekler": ["A) Di Stefano", "B) Matthews", "C) Puskas", "D) Kopa"], "cevap": "B"},
            {"soru": "Hangi hakem 3 Dünya Kupası finalini yönetmiştir?",
             "secenekler": ["A) Collina", "B) Hiçbiri, bu başarı yok", "C) Webb", "D) Elizondo"], "cevap": "B"},
            {"soru": "Futbolda 'Panenka' penaltısı adını nereden alır?",
             "secenekler": ["A) Bir şehir", "B) Antonin Panenka adlı futbolcu", "C) Bir teknik terim", "D) Bir antrenör"], "cevap": "B"},
            {"soru": "Hangi Dünya Kupası'nda ilk kez penaltı atışları uygulanmıştır?",
             "secenekler": ["A) 1970", "B) 1974", "C) 1978", "D) 1982"], "cevap": "C"},
        ],
    },
    "genel_kultur": {
        "kolay": [
            {"soru": "Türkiye'nin başkenti neresidir?",
             "secenekler": ["A) İstanbul", "B) Ankara", "C) İzmir", "D) Antalya"], "cevap": "B"},
            {"soru": "Suyun kimyasal formülü nedir?",
             "secenekler": ["A) O2", "B) H2O", "C) CO2", "D) NaCl"], "cevap": "B"},
            {"soru": "Güneş sistemindeki en büyük gezegen hangisidir?",
             "secenekler": ["A) Mars", "B) Dünya", "C) Jüpiter", "D) Satürn"], "cevap": "C"},
            {"soru": "Dünya'nın doğal uydusu nedir?",
             "secenekler": ["A) Güneş", "B) Ay", "C) Mars", "D) Venüs"], "cevap": "B"},
            {"soru": "Cumhuriyet hangi yılda ilan edildi?",
             "secenekler": ["A) 1920", "B) 1921", "C) 1922", "D) 1923"], "cevap": "D"},
            {"soru": "Dünyanın en büyük okyanusu hangisidir?",
             "secenekler": ["A) Atlantik", "B) Hint", "C) Kuzey Buz", "D) Pasifik"], "cevap": "D"},
            {"soru": "Atatürk hangi yılda doğmuştur?",
             "secenekler": ["A) 1881", "B) 1880", "C) 1882", "D) 1885"], "cevap": "A"},
            {"soru": "İstanbul Boğazı hangi iki kıtayı ayırır?",
             "secenekler": ["A) Asya-Afrika", "B) Avrupa-Asya", "C) Avrupa-Afrika", "D) Asya-Amerika"], "cevap": "B"},
            {"soru": "Hangi organ kanı pompalar?",
             "secenekler": ["A) Beyin", "B) Akciğer", "C) Kalp", "D) Böbrek"], "cevap": "C"},
            {"soru": "Termometre ne ölçer?",
             "secenekler": ["A) Ağırlık", "B) Uzunluk", "C) Sıcaklık", "D) Hız"], "cevap": "C"},
            {"soru": "Gökkuşağında kaç renk vardır?",
             "secenekler": ["A) 5", "B) 6", "C) 7", "D) 8"], "cevap": "C"},
            {"soru": "Bir yılda kaç ay vardır?",
             "secenekler": ["A) 10", "B) 11", "C) 12", "D) 13"], "cevap": "C"},
            {"soru": "Güneş hangi yönden doğar?",
             "secenekler": ["A) Batı", "B) Kuzey", "C) Güney", "D) Doğu"], "cevap": "D"},
            {"soru": "İnsan vücudunda kaç kemik vardır (yetişkin)?",
             "secenekler": ["A) 106", "B) 156", "C) 206", "D) 256"], "cevap": "C"},
            {"soru": "Hangisi bir meyve değildir?",
             "secenekler": ["A) Elma", "B) Havuç", "C) Portakal", "D) Çilek"], "cevap": "B"},
            {"soru": "Dünya'nın şekli neye benzer?",
             "secenekler": ["A) Küp", "B) Silindir", "C) Küre (geoid)", "D) Koni"], "cevap": "C"},
            {"soru": "Bir haftada kaç gün vardır?",
             "secenekler": ["A) 5", "B) 6", "C) 7", "D) 8"], "cevap": "C"},
            {"soru": "Hangi hayvan 'ormanların kralı' olarak bilinir?",
             "secenekler": ["A) Kaplan", "B) Aslan", "C) Ayı", "D) Kurt"], "cevap": "B"},
            {"soru": "Türk bayrağının renkleri nelerdir?",
             "secenekler": ["A) Kırmızı-Mavi", "B) Kırmızı-Beyaz", "C) Yeşil-Beyaz", "D) Mavi-Beyaz"], "cevap": "B"},
            {"soru": "Hangisi bir kıta değildir?",
             "secenekler": ["A) Asya", "B) Avrupa", "C) Arktik", "D) Afrika"], "cevap": "C"},
            {"soru": "Bir günde kaç saat vardır?",
             "secenekler": ["A) 12", "B) 20", "C) 24", "D) 36"], "cevap": "C"},
            {"soru": "Hangi gezegen Dünya'ya en yakındır?",
             "secenekler": ["A) Mars", "B) Venüs", "C) Merkür", "D) Jüpiter"], "cevap": "B"},
            {"soru": "İstanbul hangi ülkede?",
             "secenekler": ["A) Yunanistan", "B) İran", "C) Türkiye", "D) Mısır"], "cevap": "C"},
            {"soru": "Kaç mevsim vardır?",
             "secenekler": ["A) 2", "B) 3", "C) 4", "D) 5"], "cevap": "C"},
            {"soru": "Hangisi bir renk değildir?",
             "secenekler": ["A) Yeşil", "B) Mavi", "C) Hızlı", "D) Sarı"], "cevap": "C"},
             {"soru": "Hangisi bir sebzedir?",
             "secenekler": ["A) Elma", "B) Üzüm", "C) Domates", "D) Çilek"], "cevap": "C"},
            {"soru": "Bir üçgenin kaç kenarı vardır?",
             "secenekler": ["A) 2", "B) 3", "C) 4", "D) 5"], "cevap": "B"},
            {"soru": "Hangi hayvan süt verir?",
             "secenekler": ["A) Tavuk", "B) Yılan", "C) İnek", "D) Kurbağa"], "cevap": "C"},
            {"soru": "Bir dakikada kaç saniye vardır?",
             "secenekler": ["A) 30", "B) 45", "C) 60", "D) 100"], "cevap": "C"},
            {"soru": "Hangisi bir iletişim aracı değildir?",
             "secenekler": ["A) Telefon", "B) Mektup", "C) Televizyon", "D) Sandalye"], "cevap": "D"},
            {"soru": "Yağmur bulutları gökyüzünün neresinde oluşur?",
             "secenekler": ["A) Uzayda", "B) Atmosferde", "C) Denizde", "D) Yer altında"], "cevap": "B"},
            {"soru": "Hangi gezegen halkalara sahiptir?",
             "secenekler": ["A) Mars", "B) Venüs", "C) Satürn", "D) Merkür"], "cevap": "C"},
            {"soru": "İstiklal Marşı'nı kim yazmıştır?",
             "secenekler": ["A) Atatürk", "B) Mehmet Akif Ersoy", "C) Nazım Hikmet", "D) Yahya Kemal"], "cevap": "B"},
            {"soru": "Bir saatte kaç dakika vardır?",
             "secenekler": ["A) 30", "B) 45", "C) 60", "D) 100"], "cevap": "C"},
            {"soru": "Hangisi bir deniz hayvanıdır?",
             "secenekler": ["A) Kartal", "B) Aslan", "C) Yunus", "D) Zürafa"], "cevap": "C"},
            {"soru": "Dünyanın en büyük kıtası hangisidir?",
             "secenekler": ["A) Afrika", "B) Avrupa", "C) Asya", "D) Amerika"], "cevap": "C"},
            {"soru": "Hangisi bir müzik aleti değildir?",
             "secenekler": ["A) Gitar", "B) Piyano", "C) Mikroskop", "D) Keman"], "cevap": "C"},
            {"soru": "Suyun kaynama noktası kaç derecedir?",
             "secenekler": ["A) 50°C", "B) 75°C", "C) 100°C", "D) 150°C"], "cevap": "C"},
            {"soru": "Suyun donma noktası kaç derecedir?",
             "secenekler": ["A) -10°C", "B) 0°C", "C) 5°C", "D) 10°C"], "cevap": "B"},
            {"soru": "Hangisi bir ulaşım aracı değildir?",
             "secenekler": ["A) Otobüs", "B) Tren", "C) Buzdolabı", "D) Uçak"], "cevap": "C"},
            {"soru": "Türkiye'nin en büyük şehri hangisidir?",
             "secenekler": ["A) Ankara", "B) İzmir", "C) İstanbul", "D) Bursa"], "cevap": "C"},
            {"soru": "Hangisi bir doğal afet değildir?",
             "secenekler": ["A) Deprem", "B) Sel", "C) Yangın", "D) Piknik"], "cevap": "D"},
            {"soru": "Ayın Dünya'nın etrafındaki turu kaç gün sürer (yaklaşık)?",
             "secenekler": ["A) 7", "B) 14", "C) 27-28", "D) 60"], "cevap": "C"},
            {"soru": "Bir kilometre kaç metredir?",
             "secenekler": ["A) 100", "B) 500", "C) 1000", "D) 10000"], "cevap": "C"},
            {"soru": "Hangi organ nefes almamızı sağlar?",
             "secenekler": ["A) Kalp", "B) Böbrek", "C) Akciğer", "D) Karaciğer"], "cevap": "C"},
            {"soru": "Hangi ülkenin başkenti Paris'tir?",
             "secenekler": ["A) İspanya", "B) İtalya", "C) İngiltere", "D) Fransa"], "cevap": "D"},
            {"soru": "Hangi ülkenin başkenti Berlin'dir?",
             "secenekler": ["A) Avusturya", "B) İsviçre", "C) Almanya", "D) Hollanda"], "cevap": "C"},
            {"soru": "Hangi ülkenin başkenti Roma'dır?",
             "secenekler": ["A) İspanya", "B) İtalya", "C) Yunanistan", "D) Portekiz"], "cevap": "B"},
            {"soru": "Hangi ülkenin başkenti Londra'dır?",
             "secenekler": ["A) İrlanda", "B) İskoçya", "C) İngiltere/Birleşik Krallık", "D) Fransa"], "cevap": "C"},
            {"soru": "Dünya'nın Güneş etrafındaki turu ne kadar sürer?",
             "secenekler": ["A) 1 ay", "B) 6 ay", "C) 1 yıl", "D) 2 yıl"], "cevap": "C"},
        ],
        "orta": [
            {"soru": "Mona Lisa'yı kim yapmıştır?",
             "secenekler": ["A) Picasso", "B) Van Gogh", "C) Leonardo da Vinci", "D) Michelangelo"], "cevap": "C"},
            {"soru": "Periyodik tabloda 'Au' hangi elementtir?",
             "secenekler": ["A) Gümüş", "B) Altın", "C) Bakır", "D) Demir"], "cevap": "B"},
            {"soru": "İstanbul'un fethi hangi yıldadır?",
             "secenekler": ["A) 1299", "B) 1453", "C) 1517", "D) 1071"], "cevap": "B"},
            {"soru": "DNA'nın açılımı nedir?",
             "secenekler": ["A) Deoksiribo Nükleik Asit", "B) Dijital Nükleer Atom", "C) Doğal Nötron Asidi", "D) Dinamik Alan"], "cevap": "A"},
            {"soru": "Kızıl Gezegen hangisidir?",
             "secenekler": ["A) Jüpiter", "B) Satürn", "C) Mars", "D) Venüs"], "cevap": "C"},
            {"soru": "Nobel Barış Ödülü nerede verilir?",
             "secenekler": ["A) Stockholm", "B) Oslo", "C) Helsinki", "D) Kopenhag"], "cevap": "B"},
            {"soru": "Pi sayısının ilk 3 basamağı nedir?",
             "secenekler": ["A) 3.12", "B) 3.14", "C) 3.16", "D) 3.18"], "cevap": "B"},
            {"soru": "Osmanlı İmparatorluğu hangi yılda kuruldu?",
             "secenekler": ["A) 1071", "B) 1299", "C) 1453", "D) 1326"], "cevap": "B"},
            {"soru": "Hangi vitamin güneş ışığıyla sentezlenir?",
             "secenekler": ["A) A", "B) B12", "C) C", "D) D"], "cevap": "D"},
            {"soru": "Everest Dağı hangi iki ülke sınırındadır?",
             "secenekler": ["A) Çin-Hindistan", "B) Nepal-Çin", "C) Nepal-Hindistan", "D) Pakistan-Çin"], "cevap": "B"},
            {"soru": "Amazonlar hangi kıtadadır?",
             "secenekler": ["A) Afrika", "B) Asya", "C) Güney Amerika", "D) Avrupa"], "cevap": "C"},
            {"soru": "Türkiye hangi kıtada yer alır?",
             "secenekler": ["A) Sadece Asya", "B) Sadece Avrupa", "C) Asya ve Avrupa", "D) Afrika ve Asya"], "cevap": "C"},
            {"soru": "İlk insanlar hangi kıtada ortaya çıktı?",
             "secenekler": ["A) Asya", "B) Avrupa", "C) Afrika", "D) Amerika"], "cevap": "C"},
            {"soru": "Dünya kaç yıl önce oluşmuştur (yaklaşık)?",
             "secenekler": ["A) 1 milyar", "B) 2.5 milyar", "C) 4.5 milyar", "D) 10 milyar"], "cevap": "C"},
            {"soru": "Hangi kan grubu evrensel vericidir?",
             "secenekler": ["A) A", "B) B", "C) AB", "D) O Rh-"], "cevap": "D"},
            {"soru": "Newton hangi ülkelidir?",
             "secenekler": ["A) Almanya", "B) Fransa", "C) İngiltere", "D) İtalya"], "cevap": "C"},
            {"soru": "Dünyanın en uzun nehri hangisidir?",
             "secenekler": ["A) Amazon", "B) Nil", "C) Mississippi", "D) Tuna"], "cevap": "B"},
            {"soru": "Fotosentez sırasında bitki ne üretir?",
             "secenekler": ["A) Karbondioksit", "B) Azot", "C) Oksijen", "D) Hidrojen"], "cevap": "C"},
            {"soru": "Einstein hangi ülkede doğmuştur?",
             "secenekler": ["A) ABD", "B) İsviçre", "C) Almanya", "D) Avusturya"], "cevap": "C"},
            {"soru": "Venüs güneşe en yakın kaçıncı gezegendir?",
             "secenekler": ["A) 1.", "B) 2.", "C) 3.", "D) 4."], "cevap": "B"},
            {"soru": "Hangisi bir element değildir?",
             "secenekler": ["A) Altın", "B) Su", "C) Demir", "D) Oksijen"], "cevap": "B"},
            {"soru": "İnsan beyninde yaklaşık kaç nöron vardır?",
             "secenekler": ["A) 1 milyon", "B) 100 milyon", "C) 10 milyar", "D) 86 milyar"], "cevap": "D"},
            {"soru": "Büyük Hadron Çarpıştırıcısı (LHC) hangi ülkededir?",
             "secenekler": ["A) ABD", "B) Japonya", "C) İsviçre/Fransa sınırı", "D) Almanya"], "cevap": "C"},
            {"soru": "Işık yılı neyin birimidir?",
             "secenekler": ["A) Zaman", "B) Uzaklık", "C) Hız", "D) Enerji"], "cevap": "B"},
            {"soru": "Kurtuluş Savaşı hangi yıllar arasında yapıldı?",
             "secenekler": ["A) 1914-1918", "B) 1919-1923", "C) 1920-1922", "D) 1918-1920"], "cevap": "B"},
            {"soru": "TBMM hangi yılda açıldı?",
             "secenekler": ["A) 1919", "B) 1920", "C) 1921", "D) 1923"], "cevap": "B"},
            {"soru": "Hangisi bir programlama dili değildir?",
             "secenekler": ["A) Python", "B) Java", "C) HTML", "D) Photoshop"], "cevap": "D"},
            {"soru": "Ay'a ilk ayak basan astronot kimdir?",
             "secenekler": ["A) Buzz Aldrin", "B) Neil Armstrong", "C) Yuri Gagarin", "D) John Glenn"], "cevap": "B"},
            {"soru": "İlk bilgisayar programcısı olarak kabul edilen kişi kimdir?",
             "secenekler": ["A) Alan Turing", "B) Ada Lovelace", "C) Charles Babbage", "D) Bill Gates"], "cevap": "B"},
            {"soru": "Hangisi bir yenilenebilir enerji kaynağıdır?",
             "secenekler": ["A) Kömür", "B) Doğalgaz", "C) Rüzgar", "D) Petrol"], "cevap": "C"},
            {"soru": "İstanbul hangi yılda başkent olmaktan çıkmıştır?",
             "secenekler": ["A) 1920", "B) 1923", "C) 1925", "D) 1930"], "cevap": "B"},
            {"soru": "Çanakkale Savaşı hangi yılda olmuştur?",
             "secenekler": ["A) 1914", "B) 1915", "C) 1916", "D) 1917"], "cevap": "B"},
            {"soru": "Hangisi bir greenhouse (sera) gazı değildir?",
             "secenekler": ["A) CO2", "B) Metan", "C) Azot", "D) Su buharı"], "cevap": "C"},
            {"soru": "Yapay zeka kavramı ilk kez ne zaman ortaya atılmıştır?",
             "secenekler": ["A) 1936", "B) 1956", "C) 1970", "D) 1985"], "cevap": "B"},
            {"soru": "Bitcoin hangi yılda oluşturulmuştur?",
             "secenekler": ["A) 2005", "B) 2007", "C) 2009", "D) 2011"], "cevap": "C"},
            {"soru": "İlk akıllı telefon hangisidir?",
             "secenekler": ["A) iPhone", "B) Nokia 9000", "C) IBM Simon", "D) BlackBerry"], "cevap": "C"},
            {"soru": "Mars'ın kaç uydusu vardır?",
             "secenekler": ["A) 0", "B) 1", "C) 2", "D) 4"], "cevap": "C"},
            {"soru": "Malazgirt Savaşı hangi yılda olmuştur?",
             "secenekler": ["A) 1040", "B) 1071", "C) 1176", "D) 1299"], "cevap": "B"},
            {"soru": "Hangisi bir ada ülkesi değildir?",
             "secenekler": ["A) Japonya", "B) Küba", "C) İsviçre", "D) İzlanda"], "cevap": "C"},
            {"soru": "Ozon tabakası atmosferin hangi katmanındadır?",
             "secenekler": ["A) Troposfer", "B) Stratosfer", "C) Mezosfer", "D) Termosfer"], "cevap": "B"},
            {"soru": "Hangi ülke dünyanın en kalabalık ülkesidir (2024)?",
             "secenekler": ["A) Çin", "B) Hindistan", "C) ABD", "D) Endonezya"], "cevap": "B"},
            {"soru": "Dünyanın en büyük çölü hangisidir?",
             "secenekler": ["A) Gobi", "B) Sahra", "C) Antarktika", "D) Kalahari"], "cevap": "C"},
            {"soru": "Hangi gezegen güneş sisteminde en hızlı döner?",
             "secenekler": ["A) Dünya", "B) Mars", "C) Jüpiter", "D) Satürn"], "cevap": "C"},
            {"soru": "WWW'nin açılımı nedir?",
             "secenekler": ["A) World Wide Web", "B) World War Web", "C) Wide World Web", "D) Web Wide World"], "cevap": "A"},
            {"soru": "Hangi ülke yüzölçümü bakımından en büyüktür?",
             "secenekler": ["A) Kanada", "B) Çin", "C) ABD", "D) Rusya"], "cevap": "D"},
            {"soru": "İnsan vücudundaki en büyük organ hangisidir?",
             "secenekler": ["A) Karaciğer", "B) Beyin", "C) Deri", "D) Akciğer"], "cevap": "C"},
            {"soru": "Hangi metal oda sıcaklığında sıvıdır?",
             "secenekler": ["A) Kurşun", "B) Cıva", "C) Alüminyum", "D) Bakır"], "cevap": "B"},
            {"soru": "TCP/IP ne için kullanılır?",
             "secenekler": ["A) Görüntü işleme", "B) İnternet iletişimi", "C) Ses kayıt", "D) Şifreleme"], "cevap": "B"},
            {"soru": "Hangi hayvan en hızlı kara hayvanıdır?",
             "secenekler": ["A) Aslan", "B) At", "C) Çita", "D) Kanguru"], "cevap": "C"},
            {"soru": "Dünyanın en yüksek binası hangisidir (2024)?",
             "secenekler": ["A) Empire State", "B) Burj Khalifa", "C) Shanghai Tower", "D) One World Trade"], "cevap": "B"},
             {"soru": "Hangisi bir Güney Amerika ülkesi değildir?",
             "secenekler": ["A) Arjantin", "B) Şili", "C) Portekiz", "D) Kolombiya"], "cevap": "C"},
            {"soru": "Hangi ülke dünyanın en fazla nüfusuna sahiptir (2024)?",
             "secenekler": ["A) Çin", "B) Hindistan", "C) ABD", "D) Endonezya"], "cevap": "B"},
            {"soru": "İnternetin öncüsü sayılan ağ hangisidir?",
             "secenekler": ["A) Ethernet", "B) ARPANET", "C) WiFi", "D) Bluetooth"], "cevap": "B"},
            {"soru": "Hangi ülke Avustralya kıtasında yer alır?",
             "secenekler": ["A) Yeni Zelanda", "B) Endonezya", "C) Avustralya", "D) Fiji"], "cevap": "C"},
            {"soru": "ChatGPT'yi hangi şirket geliştirmiştir?",
             "secenekler": ["A) Google", "B) Microsoft", "C) OpenAI", "D) Meta"], "cevap": "C"},
            {"soru": "SpaceX'in kurucusu kimdir?",
             "secenekler": ["A) Jeff Bezos", "B) Bill Gates", "C) Elon Musk", "D) Mark Zuckerberg"], "cevap": "C"},
            {"soru": "Amazon şirketinin kurucusu kimdir?",
             "secenekler": ["A) Elon Musk", "B) Jeff Bezos", "C) Steve Jobs", "D) Larry Page"], "cevap": "B"},
            {"soru": "Sahra Çölü hangi kıtadadır?",
             "secenekler": ["A) Asya", "B) Güney Amerika", "C) Avustralya", "D) Afrika"], "cevap": "D"},
            {"soru": "Hangi deniz Türkiye'nin kuzeyindedir?",
             "secenekler": ["A) Akdeniz", "B) Ege Denizi", "C) Karadeniz", "D) Marmara Denizi"], "cevap": "C"},
            {"soru": "Hangi element sembolü 'Fe' dir?",
             "secenekler": ["A) Flor", "B) Fosfor", "C) Demir", "D) Fermiyum"], "cevap": "C"},
            {"soru": "Hangi organ vücuttaki zehirleri filtreler?",
             "secenekler": ["A) Kalp", "B) Karaciğer", "C) Beyin", "D) Pankreas"], "cevap": "B"},
            {"soru": "Titanic hangi yılda batmıştır?",
             "secenekler": ["A) 1905", "B) 1912", "C) 1920", "D) 1935"], "cevap": "B"},
            {"soru": "Hangi ülke dünyanın en uzun sahil şeridine sahiptir?",
             "secenekler": ["A) Avustralya", "B) ABD", "C) Kanada", "D) Rusya"], "cevap": "C"},
            {"soru": "Linux işletim sisteminin çekirdeğini kim geliştirmiştir?",
             "secenekler": ["A) Bill Gates", "B) Steve Wozniak", "C) Linus Torvalds", "D) Dennis Ritchie"], "cevap": "C"},
            {"soru": "Hangi ülkede piramitler bulunur?",
             "secenekler": ["A) Yunanistan", "B) İran", "C) Meksika ve Mısır", "D) Hindistan"], "cevap": "C"},
            {"soru": "İnsan DNA'sının yüzde kaçı şempanzelerle ortaktır?",
             "secenekler": ["A) 80%", "B) 90%", "C) 95%", "D) 98.7%"], "cevap": "D"},
            {"soru": "Kelvin sıcaklık ölçeğinde suyun kaynama noktası kaçtır?",
             "secenekler": ["A) 100", "B) 212", "C) 373", "D) 473"], "cevap": "C"},
            {"soru": "Hangi gezegenin en çok uydusu vardır?",
             "secenekler": ["A) Jüpiter", "B) Satürn", "C) Uranüs", "D) Neptün"], "cevap": "B"},
            {"soru": "GPS sistemi kaç uydu kullanır (minimum)?",
             "secenekler": ["A) 12", "B) 24", "C) 30", "D) 48"], "cevap": "B"},
            {"soru": "Bluetooth teknolojisi adını nereden almıştır?",
             "secenekler": ["A) Bir renk", "B) Viking kralı Harald Bluetooth", "C) Bir hayvan", "D) Bir şehir"], "cevap": "B"},
            {"soru": "Hangi vitamin kemik sağlığı için önemlidir?",
             "secenekler": ["A) A vitamini", "B) B vitamini", "C) C vitamini", "D) D vitamini ve Kalsiyum"], "cevap": "D"},
            {"soru": "Albert Einstein Nobel ödülünü hangi alanda almıştır?",
             "secenekler": ["A) Görelilik teorisi", "B) Fotoelektrik etki", "C) Kara delikler", "D) Kuantum mekaniği"], "cevap": "B"},
            {"soru": "Hangi ülke hem Avrupa'da hem Asya'da toprak sahibidir?",
             "secenekler": ["A) İran", "B) Mısır", "C) Türkiye ve Rusya", "D) Yunanistan"], "cevap": "C"},
            {"soru": "World Wide Web (WWW) kim tarafından icat edilmiştir?",
             "secenekler": ["A) Bill Gates", "B) Steve Jobs", "C) Tim Berners-Lee", "D) Vint Cerf"], "cevap": "C"},
            {"soru": "Hangi metal en iyi elektrik iletkenidir?",
             "secenekler": ["A) Altın", "B) Bakır", "C) Gümüş", "D) Alüminyum"], "cevap": "C"},
        ],
        "zor": [
            {"soru": "Magna Carta hangi yılda imzalandı?",
             "secenekler": ["A) 1066", "B) 1215", "C) 1453", "D) 1789"], "cevap": "B"},
            {"soru": "Heisenberg Belirsizlik İlkesi neyle ilgilidir?",
             "secenekler": ["A) Işık kırılması", "B) Konum ve momentum aynı anda kesin ölçülemez", "C) Ses yayılması", "D) Yer çekimi"], "cevap": "B"},
            {"soru": "Rosetta Taşı hangi dillerde yazılmıştır?",
             "secenekler": ["A) Latince-Arapça-Yunanca", "B) Hiyeroglif-Demotik-Antik Yunanca", "C) Sümerce-Farsça-Latince", "D) Koptça-Arapça-İbranice"], "cevap": "B"},
            {"soru": "İnsan Genomu Projesi hangi yıl tamamlandı?",
             "secenekler": ["A) 1999", "B) 2001", "C) 2003", "D) 2005"], "cevap": "C"},
            {"soru": "Periyodik tabloda 'W' hangi elementtir?",
             "secenekler": ["A) Tungsten", "B) Gümüş", "C) Kalay", "D) Çinko"], "cevap": "A"},
            {"soru": "Dünyanın en derin noktası neresidir?",
             "secenekler": ["A) Tonga Çukuru", "B) Mariana Çukuru", "C) Java Çukuru", "D) Porto Riko Çukuru"], "cevap": "B"},
            {"soru": "E=mc² formülü neyi ifade eder?",
             "secenekler": ["A) Kütle-enerji denkliği", "B) Yerçekimi", "C) Elektrik akımı", "D) Ses hızı"], "cevap": "A"},
            {"soru": "Osmanlı'nın son padişahı kimdir?",
             "secenekler": ["A) Abdülhamid II", "B) Vahdettin", "C) Reşad", "D) Abdülmecid II"], "cevap": "B"},
            {"soru": "Çernobil felaketi hangi yılda yaşandı?",
             "secenekler": ["A) 1984", "B) 1986", "C) 1988", "D) 1990"], "cevap": "B"},
            {"soru": "Nikola Tesla hangi ülkede doğmuştur?",
             "secenekler": ["A) ABD", "B) Sırbistan", "C) Hırvatistan", "D) Avusturya"], "cevap": "C"},
            {"soru": "Türkiye'nin en uzun nehri hangisidir?",
             "secenekler": ["A) Fırat", "B) Dicle", "C) Kızılırmak", "D) Sakarya"], "cevap": "C"},
            {"soru": "Hangisi bir Nobel kategorisi değildir?",
             "secenekler": ["A) Fizik", "B) Matematik", "C) Edebiyat", "D) Ekonomi"], "cevap": "B"},
            {"soru": "Matbaa kim tarafından icat edilmiştir?",
             "secenekler": ["A) Edison", "B) Gutenberg", "C) Tesla", "D) Newton"], "cevap": "B"},
            {"soru": "Fransa Devrimi hangi yılda başlamıştır?",
             "secenekler": ["A) 1776", "B) 1789", "C) 1804", "D) 1815"], "cevap": "B"},
            {"soru": "İpek Yolu nereyi nereye bağlıyordu?",
             "secenekler": ["A) Afrika-Avrupa", "B) Çin-Akdeniz", "C) Hindistan-Amerika", "D) Mısır-Roma"], "cevap": "B"},
            {"soru": "Hangi bilim insanı radyoaktiviteyi keşfetmiştir?",
             "secenekler": ["A) Curie", "B) Becquerel", "C) Rutherford", "D) Bohr"], "cevap": "B"},
            {"soru": "Osmanlı İmparatorluğu hangi yılda sona erdi?",
             "secenekler": ["A) 1918", "B) 1920", "C) 1922", "D) 1924"], "cevap": "C"},
            {"soru": "İlk antibiyotik hangisidir?",
             "secenekler": ["A) Aspirin", "B) Penisilin", "C) İbuprofen", "D) Morfin"], "cevap": "B"},
            {"soru": "Kanuni Sultan Süleyman kaç yıl tahtta kalmıştır?",
             "secenekler": ["A) 36", "B) 42", "C) 46", "D) 50"], "cevap": "C"},
            {"soru": "Plüton neden gezegen sayılmıyor?",
             "secenekler": ["A) Çok küçük", "B) Yörüngesini temizleyemedi", "C) Uydusu yok", "D) Güneşe çok uzak"], "cevap": "B"},
            {"soru": "Sanayi Devrimi hangi ülkede başlamıştır?",
             "secenekler": ["A) Fransa", "B) Almanya", "C) ABD", "D) İngiltere"], "cevap": "D"},
            {"soru": "Soğuk Savaş hangi yıllar arasında yaşanmıştır?",
             "secenekler": ["A) 1939-1945", "B) 1947-1991", "C) 1950-1980", "D) 1960-2000"], "cevap": "B"},
            {"soru": "Berlin Duvarı hangi yılda yıkılmıştır?",
             "secenekler": ["A) 1987", "B) 1989", "C) 1991", "D) 1993"], "cevap": "B"},
            {"soru": "Rönesans hangi ülkede başlamıştır?",
             "secenekler": ["A) Fransa", "B) İngiltere", "C) İtalya", "D) Almanya"], "cevap": "C"},
            {"soru": "Atom bombası ilk kez nerede kullanılmıştır?",
             "secenekler": ["A) Nagasaki", "B) Hiroşima", "C) Tokyo", "D) Osaka"], "cevap": "B"},
            {"soru": "Süveyş Kanalı hangi iki denizi birbirine bağlar?",
             "secenekler": ["A) Akdeniz-Kızıldeniz", "B) Akdeniz-Karadeniz", "C) Atlantik-Pasifik", "D) Kızıldeniz-Hint Okyanusu"], "cevap": "A"},
            {"soru": "Panama Kanalı hangi iki okyanusu birbirine bağlar?",
             "secenekler": ["A) Atlantik-Hint", "B) Pasifik-Hint", "C) Atlantik-Pasifik", "D) Kuzey Buz-Atlantik"], "cevap": "C"},
            {"soru": "Fatih Sultan Mehmet İstanbul'u fethettiğinde kaç yaşındaydı?",
             "secenekler": ["A) 19", "B) 21", "C) 23", "D) 25"], "cevap": "B"},
            {"soru": "Marie Curie kaç Nobel ödülü almıştır?",
             "secenekler": ["A) 1", "B) 2", "C) 3", "D) 0"], "cevap": "B"},
            {"soru": "Hangi element periyodik tabloda en hafiftir?",
             "secenekler": ["A) Helyum", "B) Lityum", "C) Hidrojen", "D) Karbon"], "cevap": "C"},
            {"soru": "Fibonacci dizisinde 1, 1, 2, 3, 5'ten sonra gelen sayı nedir?",
             "secenekler": ["A) 7", "B) 8", "C) 9", "D) 10"], "cevap": "B"},
            {"soru": "Galile hangi ülkelidir?",
             "secenekler": ["A) Fransa", "B) İngiltere", "C) İtalya", "D) Almanya"], "cevap": "C"},
            {"soru": "Darwin'in ünlü eseri hangisidir?",
             "secenekler": ["A) Principia", "B) Türlerin Kökeni", "C) Kapital", "D) Savaş ve Barış"], "cevap": "B"},
            {"soru": "Newton'un ünlü eseri hangisidir?",
             "secenekler": ["A) Principia", "B) Türlerin Kökeni", "C) Opticks", "D) İtiraflar"], "cevap": "A"},
            {"soru": "Ampulü kim icat etmiştir?",
             "secenekler": ["A) Tesla", "B) Bell", "C) Edison", "D) Watt"], "cevap": "C"},
            {"soru": "Telefonu kim icat etmiştir?",
             "secenekler": ["A) Edison", "B) Tesla", "C) Marconi", "D) Bell"], "cevap": "D"},
            {"soru": "İlk uçağı kim icat etmiştir?",
             "secenekler": ["A) Da Vinci", "B) Wright Kardeşler", "C) Santos Dumont", "D) Lindbergh"], "cevap": "B"},
            {"soru": "Hangisi bir Akdeniz ülkesi değildir?",
             "secenekler": ["A) İspanya", "B) İtalya", "C) İsviçre", "D) Yunanistan"], "cevap": "C"},
            {"soru": "BM (Birleşmiş Milletler) hangi yılda kurulmuştur?",
             "secenekler": ["A) 1940", "B) 1945", "C) 1950", "D) 1955"], "cevap": "B"},
            {"soru": "NATO hangi yılda kurulmuştur?",
             "secenekler": ["A) 1945", "B) 1949", "C) 1952", "D) 1955"], "cevap": "B"},
            {"soru": "Hangi bilim dalı yıldızları inceler?",
             "secenekler": ["A) Jeoloji", "B) Biyoloji", "C) Astronomi", "D) Meteoroloji"], "cevap": "C"},
            {"soru": "Pasteur neyi keşfetmiştir?",
             "secenekler": ["A) Penisilin", "B) Aşı ve pastörizasyon", "C) Röntgen", "D) DNA"], "cevap": "B"},
            {"soru": "Hangi savaş 1914-1918 yılları arasında olmuştur?",
             "secenekler": ["A) 2. Dünya Savaşı", "B) 1. Dünya Savaşı", "C) Kore Savaşı", "D) Vietnam Savaşı"], "cevap": "B"},
            {"soru": "Barok döneminin en ünlü bestecisi kimdir?",
             "secenekler": ["A) Mozart", "B) Beethoven", "C) Bach", "D) Chopin"], "cevap": "C"},
            {"soru": "Hangi ülke dünyanın en küçük ülkesidir?",
             "secenekler": ["A) Monako", "B) San Marino", "C) Vatikan", "D) Lihtenştayn"], "cevap": "C"},
            {"soru": "Amazonlar hangi iki okyanus arasında yer alır?",
             "secenekler": ["A) Atlantik-Pasifik", "B) Hint-Atlantik", "C) Pasifik-Hint", "D) Atlantik-Kuzey Buz"], "cevap": "A"},
            {"soru": "İlk uzaya giden insan kimdir?",
             "secenekler": ["A) Neil Armstrong", "B) Buzz Aldrin", "C) Yuri Gagarin", "D) John Glenn"], "cevap": "C"},
            {"soru": "Hangi vitamin eksikliği skorbüt hastalığına neden olur?",
             "secenekler": ["A) A vitamini", "B) B vitamini", "C) C vitamini", "D) D vitamini"], "cevap": "C"},
            {"soru": "Kolomb Amerika'yı hangi yılda keşfetmiştir?",
             "secenekler": ["A) 1453", "B) 1492", "C) 1500", "D) 1521"], "cevap": "B"},
             {"soru": "Turing Testi neyi ölçer?",
             "secenekler": ["A) Bilgisayar hızını", "B) Makinenin insan gibi düşünüp düşünemediğini", "C) İnternet hızını", "D) Hafıza kapasitesini"], "cevap": "B"},
            {"soru": "Hangi antlaşma ile Osmanlı İmparatorluğu resmen sona ermiştir?",
             "secenekler": ["A) Sevr", "B) Lozan", "C) Mudanya", "D) Mondros"], "cevap": "B"},
            {"soru": "Lozan Antlaşması hangi yılda imzalanmıştır?",
             "secenekler": ["A) 1920", "B) 1921", "C) 1922", "D) 1923"], "cevap": "D"},
            {"soru": "Hangi bilim insanı penisilin'i keşfetmiştir?",
             "secenekler": ["A) Pasteur", "B) Koch", "C) Fleming", "D) Jenner"], "cevap": "C"},
            {"soru": "Avrupa Birliği kaç yılında kurulmuştur (Maastricht)?",
             "secenekler": ["A) 1985", "B) 1989", "C) 1992", "D) 1995"], "cevap": "C"},
            {"soru": "Hangi element insanlar için en tehlikeli radyoaktif elementtir?",
             "secenekler": ["A) Uranyum", "B) Polonyum", "C) Radyum", "D) Toryum"], "cevap": "B"},
            {"soru": "Oksijenin periyodik tablodaki atom numarası kaçtır?",
             "secenekler": ["A) 6", "B) 7", "C) 8", "D) 9"], "cevap": "C"},
            {"soru": "Karbonun periyodik tablodaki atom numarası kaçtır?",
             "secenekler": ["A) 4", "B) 5", "C) 6", "D) 7"], "cevap": "C"},
            {"soru": "Hangi savaşta tank ilk kez kullanılmıştır?",
             "secenekler": ["A) 2. Dünya Savaşı", "B) 1. Dünya Savaşı", "C) Kore Savaşı", "D) Kırım Savaşı"], "cevap": "B"},
            {"soru": "Göbeklitepe hangi şehirdedir?",
             "secenekler": ["A) Diyarbakır", "B) Şanlıurfa", "C) Mardin", "D) Gaziantep"], "cevap": "B"},
            {"soru": "Göbeklitepe kaç yıl önce inşa edilmiştir (yaklaşık)?",
             "secenekler": ["A) 5.000", "B) 8.000", "C) 12.000", "D) 15.000"], "cevap": "C"},
            {"soru": "Hangi medeniyetin yazısı henüz çözülememiştir?",
             "secenekler": ["A) Mısır hiyeroglifi", "B) Sümer çivi yazısı", "C) Girit Linear A", "D) Fenike alfabesi"], "cevap": "C"},
            {"soru": "Voyager 1 uzay aracı ne zaman fırlatılmıştır?",
             "secenekler": ["A) 1969", "B) 1972", "C) 1977", "D) 1981"], "cevap": "C"},
            {"soru": "Hangi ülke nükleer silah sahibi değildir?",
             "secenekler": ["A) İsrail", "B) Pakistan", "C) Almanya", "D) Hindistan"], "cevap": "C"},
            {"soru": "Moore Yasası neyi öngörür?",
             "secenekler": ["A) Transistör sayısının her 2 yılda ikiye katlanması", "B) İnternet hızının artması", "C) Enerji tüketiminin azalması", "D) Bellek kapasitesinin düşmesi"], "cevap": "A"},
            {"soru": "TCP protokolünü kim geliştirmiştir?",
             "secenekler": ["A) Tim Berners-Lee", "B) Vint Cerf ve Bob Kahn", "C) Dennis Ritchie", "D) Linus Torvalds"], "cevap": "B"},
            {"soru": "Hangi felsefeci 'Düşünüyorum, öyleyse varım' demiştir?",
             "secenekler": ["A) Sokrates", "B) Aristoteles", "C) Descartes", "D) Kant"], "cevap": "C"},
            {"soru": "Hangi antik kent Türkiye'de değildir?",
             "secenekler": ["A) Efes", "B) Troya", "C) Petra", "D) Pergamon"], "cevap": "C"},
            {"soru": "Hangi gezegen 'yatan' eksen eğimine sahiptir?",
             "secenekler": ["A) Mars", "B) Venüs", "C) Uranüs", "D) Neptün"], "cevap": "C"},
            {"soru": "Hangi hayvan sonar (ekolokasyon) kullanır?",
             "secenekler": ["A) Kartal", "B) Yarasa", "C) Kedi", "D) Köpek"], "cevap": "B"},
            {"soru": "İlk programlama dili hangisidir?",
             "secenekler": ["A) C", "B) BASIC", "C) FORTRAN", "D) Assembly"], "cevap": "C"},
            {"soru": "Kapadokya hangi bölgededir?",
             "secenekler": ["A) Ege", "B) Akdeniz", "C) İç Anadolu", "D) Karadeniz"], "cevap": "C"},
            {"soru": "Hangi bilim insanı yerçekimi dalgalarını öngörmüştür?",
             "secenekler": ["A) Newton", "B) Einstein", "C) Hawking", "D) Bohr"], "cevap": "B"},
            {"soru": "Yerçekimi dalgaları ilk kez ne zaman tespit edilmiştir?",
             "secenekler": ["A) 2005", "B) 2010", "C) 2015", "D) 2020"], "cevap": "C"},
            {"soru": "Hangi ülke dünyanın en büyük altın üreticisidir (2024)?",
             "secenekler": ["A) ABD", "B) Avustralya", "C) Çin", "D) Rusya"], "cevap": "C"},
        ],
        "cok_zor": [
            {"soru": "Schrödinger'in kedisi deneyi hangi alanla ilgilidir?",
             "secenekler": ["A) Biyoloji", "B) Kimya", "C) Kuantum fiziği", "D) Jeoloji"], "cevap": "C"},
            {"soru": "Görelilik teorisine göre ışık hızına yaklaşan cismin kütlesi ne olur?",
             "secenekler": ["A) Azalır", "B) Değişmez", "C) Artar", "D) Yok olur"], "cevap": "C"},
            {"soru": "Rosalind Franklin en çok hangi keşfe katkı sağlamıştır?",
             "secenekler": ["A) Atom modeli", "B) DNA yapısı", "C) Kara delikler", "D) Aşı geliştirme"], "cevap": "B"},
            {"soru": "Sıfır sayısını ilk kullanan uygarlık hangisidir?",
             "secenekler": ["A) Mısır", "B) Yunan", "C) Maya/Hint", "D) Çin"], "cevap": "C"},
            {"soru": "Higgs bozonu ne zaman deneysel olarak kanıtlandı?",
             "secenekler": ["A) 2008", "B) 2010", "C) 2012", "D) 2015"], "cevap": "C"},
            {"soru": "Fermat'ın Son Teoremi hangi yılda kanıtlanmıştır?",
             "secenekler": ["A) 1993", "B) 1995", "C) 1998", "D) 2000"], "cevap": "B"},
            {"soru": "Karanlık madde evrenin yaklaşık yüzde kaçını oluşturur?",
             "secenekler": ["A) %5", "B) %15", "C) %27", "D) %68"], "cevap": "C"},
            {"soru": "Kuantum dolanıklık ne demektir?",
             "secenekler": ["A) Parçacıkların aynı yerde olması", "B) Parçacıkların birbirine bağımlı durumda olması", "C) Işığın yavaşlaması", "D) Atomların bölünmesi"], "cevap": "B"},
            {"soru": "Hubble sabiti neyi ölçer?",
             "secenekler": ["A) Yıldız parlaklığı", "B) Evrenin genişleme hızı", "C) Gezegen kütlesi", "D) Işık hızı"], "cevap": "B"},
            {"soru": "CRISPR teknolojisi ne için kullanılır?",
             "secenekler": ["A) Yapay zeka", "B) Gen düzenleme", "C) Nükleer enerji", "D) Uzay yolculuğu"], "cevap": "B"},
            {"soru": "Riemann hipotezi hangi konuyla ilgilidir?",
             "secenekler": ["A) Geometri", "B) Asal sayılar", "C) Olasılık", "D) Cebir"], "cevap": "B"},
            {"soru": "Planck uzunluğu yaklaşık kaç metredir?",
             "secenekler": ["A) 10^-15", "B) 10^-25", "C) 10^-35", "D) 10^-45"], "cevap": "C"},
            {"soru": "Karanlık enerji evrenin yaklaşık yüzde kaçını oluşturur?",
             "secenekler": ["A) %5", "B) %27", "C) %50", "D) %68"], "cevap": "D"},
            {"soru": "Gödel'in Eksiklik Teoremleri hangi alanla ilgilidir?",
             "secenekler": ["A) Fizik", "B) Matematik", "C) Biyoloji", "D) Felsefe"], "cevap": "B"},
            {"soru": "Hawking radyasyonu ne ile ilgilidir?",
             "secenekler": ["A) Güneş", "B) Nötron yıldızları", "C) Kara delikler", "D) Nebulalar"], "cevap": "C"},
            {"soru": "Antimadde ilk kez ne zaman keşfedilmiştir?",
             "secenekler": ["A) 1928", "B) 1932", "C) 1945", "D) 1955"], "cevap": "B"},
            {"soru": "Sicim teorisi kaç boyut öngörmektedir?",
             "secenekler": ["A) 4", "B) 7", "C) 10 veya 11", "D) 26"], "cevap": "C"},
            {"soru": "Nötron yıldızı nedir?",
             "secenekler": ["A) Yeni oluşan yıldız", "B) Süpernova sonrası çökmüş çekirdek", "C) Kara delik", "D) Gezegen"], "cevap": "B"},
            {"soru": "Hangi bilim insanı özel göreliliği formüle etmiştir?",
             "secenekler": ["A) Newton", "B) Bohr", "C) Einstein", "D) Planck"], "cevap": "C"},
            {"soru": "Standart Model'de kaç temel kuvvet vardır?",
             "secenekler": ["A) 2", "B) 3", "C) 4", "D) 5"], "cevap": "C"},
            {"soru": "Çift yarık deneyi neyi kanıtlar?",
             "secenekler": ["A) Yerçekimi", "B) Dalga-parçacık ikiliği", "C) Manyetik alan", "D) Sürtünme"], "cevap": "B"},
            {"soru": "Evrenin yaşı yaklaşık kaç milyar yıldır?",
             "secenekler": ["A) 8.7", "B) 10.2", "C) 13.8", "D) 18.5"], "cevap": "C"},
            {"soru": "Kozmik mikrodalga arka plan radyasyonu ne zaman keşfedildi?",
             "secenekler": ["A) 1955", "B) 1965", "C) 1975", "D) 1985"], "cevap": "B"},
            {"soru": "Hangi parçacık 'Tanrı Parçacığı' olarak da bilinir?",
             "secenekler": ["A) Foton", "B) Nötrino", "C) Higgs bozonu", "D) Kuark"], "cevap": "C"},
            {"soru": "Mutlak sıfır kaç Kelvin'dir?",
             "secenekler": ["A) -100 K", "B) -273 K", "C) 0 K", "D) 1 K"], "cevap": "C"},
            {"soru": "Hangi matematik problemi '7 Milenyum problemi'nden biridir?",
             "secenekler": ["A) Fermat teoremi", "B) P vs NP", "C) Goldbach sanısı", "D) İkiz asal sanısı"], "cevap": "B"},
            {"soru": "İlk yapay uydu hangisidir?",
             "secenekler": ["A) Explorer 1", "B) Sputnik 1", "C) Vostok 1", "D) Telstar"], "cevap": "B"},
            {"soru": "Hangi fizikçi kara delik kavramını ilk kez tanımlamıştır?",
             "secenekler": ["A) Einstein", "B) Hawking", "C) Schwarzschild", "D) Penrose"], "cevap": "C"},
            {"soru": "Dünyanın manyetik alanı ne tarafından oluşturulur?",
             "secenekler": ["A) Atmosfer", "B) Mantonun hareketi", "C) Dış çekirdeğin hareketi", "D) Kabuk"], "cevap": "C"},
            {"soru": "Hangi element en yüksek erime noktasına sahiptir?",
             "secenekler": ["A) Demir", "B) Tungsten", "C) Karbon", "D) Osmiyum"], "cevap": "B"},
            {"soru": "Bell Eşitsizliği neyi test eder?",
             "secenekler": ["A) Işık hızını", "B) Yerel gerçekçiliği", "C) Kütle çekimini", "D) Entropi artışını"], "cevap": "B"},
            {"soru": "Hangi teoriye göre evren büyük bir patlama ile başlamıştır?",
             "secenekler": ["A) Durağan Evren", "B) Big Bang", "C) Sicim Teorisi", "D) Çoklu Evren"], "cevap": "B"},
            {"soru": "Chandrasekar limiti neyi belirler?",
             "secenekler": ["A) Yıldız yaşı", "B) Beyaz cüce üst kütle sınırı", "C) Galaksi boyutu", "D) Gezegen sayısı"], "cevap": "B"},
            {"soru": "RNA'nın DNA'dan temel farkı nedir?",
             "secenekler": ["A) Çift sarmallıdır", "B) Tek sarmallıdır ve riboz şekeri içerir", "C) Protein içerir", "D) Yağ içerir"], "cevap": "B"},
            {"soru": "Hangi deney dalga-parçacık ikiliğini göstermiştir?",
             "secenekler": ["A) Michelson-Morley", "B) Millikan yağ damlası", "C) Çift yarık deneyi", "D) Cavendish deneyi"], "cevap": "C"},
            {"soru": "Entropi kavramı hangi termodinamik yasasıyla ilişkilidir?",
             "secenekler": ["A) Birinci yasa", "B) İkinci yasa", "C) Üçüncü yasa", "D) Sıfırıncı yasa"], "cevap": "B"},
            {"soru": "Hangi bilim insanı periyodik tabloyu oluşturmuştur?",
             "secenekler": ["A) Dalton", "B) Mendeleev", "C) Bohr", "D) Lavoisier"], "cevap": "B"},
            {"soru": "Kuantum bilgisayarlar klasik bitler yerine ne kullanır?",
             "secenekler": ["A) Megabit", "B) Nörobit", "C) Kübit", "D) Fotonbit"], "cevap": "C"},
            {"soru": "Drake Denklemi neyi tahmin etmeye çalışır?",
             "secenekler": ["A) Evrenin yaşını", "B) Galaksideki iletişim kurabilecek uygarlık sayısını", "C) Yıldız sayısını", "D) Kara delik kütlesini"], "cevap": "B"},
            {"soru": "Hangi fenomen ışığın dalga boyunun uzamasıdır?",
             "secenekler": ["A) Mavi kayma", "B) Kırmızı kayma", "C) Doppler etkisi", "D) B ve C doğru"], "cevap": "D"},
             {"soru": "Olber'in Paradoksu neyle ilgilidir?",
             "secenekler": ["A) Karanlık madde", "B) Gece gökyüzünün neden karanlık olduğu", "C) Kara delikler", "D) Işık hızı"], "cevap": "B"},
            {"soru": "Hangi teorem 'bir haritayı boyamak için en fazla 4 renk yeter' der?",
             "secenekler": ["A) Fermat teoremi", "B) Dört renk teoremi", "C) Euler teoremi", "D) Gödel teoremi"], "cevap": "B"},
            {"soru": "Von Neumann mimarisi neyi tanımlar?",
             "secenekler": ["A) İnternet protokolü", "B) Bilgisayar mimarisi", "C) Yapay zeka modeli", "D) Kuantum hesaplama"], "cevap": "B"},
            {"soru": "Hangi parçacık kütlesizdir?",
             "secenekler": ["A) Elektron", "B) Proton", "C) Foton", "D) Nötron"], "cevap": "C"},
            {"soru": "Kara deliğin olay ufku nedir?",
             "secenekler": ["A) Merkezindeki nokta", "B) Işığın bile kaçamadığı sınır", "C) Dış katmanı", "D) Çekim alanı"], "cevap": "B"},
            {"soru": "Hangi bilim insanı 'evrenin genişlediğini' keşfetmiştir?",
             "secenekler": ["A) Einstein", "B) Newton", "C) Hubble", "D) Galileo"], "cevap": "C"},
            {"soru": "Ockham'ın Usturası ne demektir?",
             "secenekler": ["A) En basit açıklama genellikle doğrudur", "B) Her şeyin bir nedeni vardır", "C) Hiçbir şey kesin değildir", "D) Bilim her şeyi açıklayabilir"], "cevap": "A"},
            {"soru": "Nash Dengesi hangi alanla ilgilidir?",
             "secenekler": ["A) Fizik", "B) Oyun teorisi", "C) Biyoloji", "D) Kimya"], "cevap": "B"},
            {"soru": "Hangi bilim insanı 'kaos teorisi' ile ünlüdür?",
             "secenekler": ["A) Feynman", "B) Lorenz", "C) Bohr", "D) Dirac"], "cevap": "B"},
            {"soru": "Kelebek etkisi hangi teoriyle ilişkilidir?",
             "secenekler": ["A) Görelilik", "B) Kaos teorisi", "C) Kuantum", "D) Sicim teorisi"], "cevap": "B"},
            {"soru": "Hangi algoritma internette en çok kullanılan şifreleme yöntemidir?",
             "secenekler": ["A) DES", "B) AES", "C) RSA", "D) MD5"], "cevap": "B"},
            {"soru": "Turing makinesi kavramı hangi yılda ortaya atılmıştır?",
             "secenekler": ["A) 1930", "B) 1936", "C) 1942", "D) 1950"], "cevap": "B"},
            {"soru": "Hangi element en yoğun doğal elementtir?",
             "secenekler": ["A) Altın", "B) Platin", "C) Osmiyum", "D) İridyum"], "cevap": "C"},
            {"soru": "Maxwell denklemleri neyi tanımlar?",
             "secenekler": ["A) Yerçekimi", "B) Elektromanyetizma", "C) Termodinamik", "D) Nükleer kuvvet"], "cevap": "B"},
            {"soru": "Hangi bilim insanı 'belirsizlik ilkesi'ni formüle etmiştir?",
             "secenekler": ["A) Bohr", "B) Planck", "C) Heisenberg", "D) Schrödinger"], "cevap": "C"},
            {"soru": "Fibonacci sayılarının altın orana yakınsama özelliği var mıdır?",
             "secenekler": ["A) Hayır", "B) Evet, 1.618...'e yakınsar", "C) Sadece çift sayılarda", "D) Sadece asal sayılarda"], "cevap": "B"},
            {"soru": "Hangi gezegen güneş sisteminde en güçlü manyetik alana sahiptir?",
             "secenekler": ["A) Dünya", "B) Mars", "C) Jüpiter", "D) Satürn"], "cevap": "C"},
            {"soru": "Dirac denklemi neyi tanımlar?",
             "secenekler": ["A) Elektron davranışını relativistik olarak", "B) Proton kütlesini", "C) Nötron yıldızlarını", "D) Kara delikleri"], "cevap": "A"},
            {"soru": "Hangi deney ilk yapay nükleer reaksiyonu gerçekleştirmiştir?",
             "secenekler": ["A) Manhattan Projesi", "B) Rutherford'un 1917 deneyi", "C) Fermi'nin Chicago kazanı", "D) Chadwick'in nötron keşfi"], "cevap": "B"},
            {"soru": "Doppler etkisi neyi açıklar?",
             "secenekler": ["A) Işığın kırılmasını", "B) Hareket eden kaynaktan gelen dalganın frekans değişimini", "C) Yerçekimini", "D) Manyetik alanı"], "cevap": "B"},
            {"soru": "Kardashev ölçeği neyi sınıflandırır?",
             "secenekler": ["A) Yıldız büyüklüklerini", "B) Medeniyetlerin enerji kullanım düzeylerini", "C) Gezegen tiplerini", "D) Galaksi şekillerini"], "cevap": "B"},
            {"soru": "Hangi matematikçi sonsuzluk kavramını formalize etmiştir?",
             "secenekler": ["A) Euler", "B) Gauss", "C) Cantor", "D) Hilbert"], "cevap": "C"},
            {"soru": "Poincaré Sanısı hangi alanda kanıtlanmıştır?",
             "secenekler": ["A) Cebir", "B) Topoloji", "C) İstatistik", "D) Geometri"], "cevap": "B"},
            {"soru": "Poincaré Sanısını kim kanıtlamıştır?",
             "secenekler": ["A) Andrew Wiles", "B) Terence Tao", "C) Grigori Perelman", "D) John Nash"], "cevap": "C"},
            {"soru": "Hangi fenomen süperiletkenlikte gözlemlenir?",
             "secenekler": ["A) Sıfır direnç ve Meissner etkisi", "B) Sonsuz direnç", "C) Manyetik alan artışı", "D) Işık emisyonu"], "cevap": "A"},
        ],
    }
}