"""
Takım Bilmece - Takım Verileri
70 yeni takım, her biri yıl + ilk 11 + bayraklar + isimler
"""

ALL_TEAMS = [
    # ==================== AVRUPA KULÜP TAKIMLARI ====================
    {
        "name": "Real Madrid", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "kostarika", "name": "Navas"},
            {"pos": "RB", "flag": "ispanya", "name": "Carvajal"},
            {"pos": "CB", "flag": "ispanya", "name": "Ramos"},
            {"pos": "CB", "flag": "fransa", "name": "Varane"},
            {"pos": "LB", "flag": "brezilya", "name": "Marcelo"},
            {"pos": "CM", "flag": "brezilya", "name": "Casemiro"},
            {"pos": "CM", "flag": "almanya", "name": "Kroos"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Modric"},
            {"pos": "RW", "flag": "galler", "name": "Bale"},
            {"pos": "ST", "flag": "fransa", "name": "Benzema"},
            {"pos": "LW", "flag": "portekiz", "name": "Ronaldo"},
        ],
        "options": ["Real Madrid", "Barcelona", "Bayern Munih", "Atletico Madrid"],
        "answer": 0
    },
    {
        "name": "Real Madrid", "year": "2002",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Casillas"},
            {"pos": "RB", "flag": "ispanya", "name": "Salgado"},
            {"pos": "CB", "flag": "ispanya", "name": "Hierro"},
            {"pos": "CB", "flag": "ispanya", "name": "Helguera"},
            {"pos": "LB", "flag": "brezilya", "name": "Roberto Carlos"},
            {"pos": "CM", "flag": "fransa", "name": "Makelele"},
            {"pos": "CM", "flag": "fransa", "name": "Zidane"},
            {"pos": "CM", "flag": "ispanya", "name": "Solari"},
            {"pos": "RW", "flag": "portekiz", "name": "Figo"},
            {"pos": "ST", "flag": "brezilya", "name": "Ronaldo"},
            {"pos": "LW", "flag": "ispanya", "name": "Raul"},
        ],
        "options": ["Barcelona", "Real Madrid", "Juventus", "Bayern Munih"],
        "answer": 1
    },
    {
        "name": "Barcelona", "year": "2009",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Valdes"},
            {"pos": "RB", "flag": "brezilya", "name": "Dani Alves"},
            {"pos": "CB", "flag": "ispanya", "name": "Pique"},
            {"pos": "CB", "flag": "ispanya", "name": "Puyol"},
            {"pos": "LB", "flag": "fransa", "name": "Abidal"},
            {"pos": "CM", "flag": "ispanya", "name": "Busquets"},
            {"pos": "CM", "flag": "ispanya", "name": "Xavi"},
            {"pos": "CM", "flag": "ispanya", "name": "Iniesta"},
            {"pos": "RW", "flag": "arjantin", "name": "Messi"},
            {"pos": "ST", "flag": "kamerun", "name": "Eto'o"},
            {"pos": "LW", "flag": "fransa", "name": "Henry"},
        ],
        "options": ["Real Madrid", "Bayern Munih", "Barcelona", "Manchester United"],
        "answer": 2
    },
    {
        "name": "Barcelona", "year": "2015",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Ter Stegen"},
            {"pos": "RB", "flag": "brezilya", "name": "Dani Alves"},
            {"pos": "CB", "flag": "ispanya", "name": "Pique"},
            {"pos": "CB", "flag": "arjantin", "name": "Mascherano"},
            {"pos": "LB", "flag": "ispanya", "name": "Alba"},
            {"pos": "CM", "flag": "ispanya", "name": "Busquets"},
            {"pos": "CM", "flag": "ispanya", "name": "Iniesta"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Rakitic"},
            {"pos": "RW", "flag": "arjantin", "name": "Messi"},
            {"pos": "ST", "flag": "uruguay", "name": "Suarez"},
            {"pos": "LW", "flag": "brezilya", "name": "Neymar"},
        ],
        "options": ["Real Madrid", "Barcelona", "Bayern Munih", "Juventus"],
        "answer": 1
    },
    {
        "name": "Liverpool", "year": "2019",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Alisson"},
            {"pos": "RB", "flag": "ingiltere", "name": "Alexander-Arnold"},
            {"pos": "CB", "flag": "hollanda", "name": "Van Dijk"},
            {"pos": "CB", "flag": "kamerun", "name": "Matip"},
            {"pos": "LB", "flag": "iskocya", "name": "Robertson"},
            {"pos": "CM", "flag": "brezilya", "name": "Fabinho"},
            {"pos": "CM", "flag": "ingiltere", "name": "Henderson"},
            {"pos": "CM", "flag": "hollanda", "name": "Wijnaldum"},
            {"pos": "RW", "flag": "misir", "name": "Salah"},
            {"pos": "ST", "flag": "brezilya", "name": "Firmino"},
            {"pos": "LW", "flag": "senegal", "name": "Mane"},
        ],
        "options": ["Manchester City", "Liverpool", "Tottenham", "Chelsea"],
        "answer": 1
    },
    {
        "name": "Manchester United", "year": "2008",
        "players": [
            {"pos": "GK", "flag": "hollanda", "name": "Van der Sar"},
            {"pos": "RB", "flag": "ingiltere", "name": "Brown"},
            {"pos": "CB", "flag": "ingiltere", "name": "Ferdinand"},
            {"pos": "CB", "flag": "sirbistan", "name": "Vidic"},
            {"pos": "LB", "flag": "fransa", "name": "Evra"},
            {"pos": "CM", "flag": "ingiltere", "name": "Carrick"},
            {"pos": "CM", "flag": "ingiltere", "name": "Scholes"},
            {"pos": "RW", "flag": "portekiz", "name": "Ronaldo"},
            {"pos": "AM", "flag": "ingiltere", "name": "Rooney"},
            {"pos": "LW", "flag": "galler", "name": "Giggs"},
            {"pos": "ST", "flag": "arjantin", "name": "Tevez"},
        ],
        "options": ["Chelsea", "Liverpool", "Manchester United", "Arsenal"],
        "answer": 2
    },
    {
        "name": "Bayern Munih", "year": "2020",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Neuer"},
            {"pos": "RB", "flag": "almanya", "name": "Kimmich"},
            {"pos": "CB", "flag": "almanya", "name": "Boateng"},
            {"pos": "CB", "flag": "avusturya", "name": "Alaba"},
            {"pos": "LB", "flag": "kanada", "name": "Davies"},
            {"pos": "CM", "flag": "ispanya", "name": "Thiago"},
            {"pos": "CM", "flag": "almanya", "name": "Goretzka"},
            {"pos": "AM", "flag": "almanya", "name": "Muller"},
            {"pos": "RW", "flag": "fransa", "name": "Coman"},
            {"pos": "ST", "flag": "polonya", "name": "Lewandowski"},
            {"pos": "LW", "flag": "almanya", "name": "Gnabry"},
        ],
        "options": ["Bayern Munih", "Dortmund", "PSG", "Manchester City"],
        "answer": 0
    },
    {
        "name": "Chelsea", "year": "2021",
        "players": [
            {"pos": "GK", "flag": "senegal", "name": "Mendy"},
            {"pos": "CB", "flag": "almanya", "name": "Rudiger"},
            {"pos": "CB", "flag": "danimarka", "name": "Christensen"},
            {"pos": "CB", "flag": "brezilya", "name": "Thiago Silva"},
            {"pos": "RB", "flag": "ingiltere", "name": "James"},
            {"pos": "LB", "flag": "ispanya", "name": "Alonso"},
            {"pos": "CM", "flag": "fransa", "name": "Kante"},
            {"pos": "CM", "flag": "italya", "name": "Jorginho"},
            {"pos": "AM", "flag": "almanya", "name": "Havertz"},
            {"pos": "ST", "flag": "almanya", "name": "Werner"},
            {"pos": "LW", "flag": "ingiltere", "name": "Mount"},
        ],
        "options": ["Manchester City", "Chelsea", "Liverpool", "PSG"],
        "answer": 1
    },
    {
        "name": "Inter Milan", "year": "2023",
        "players": [
            {"pos": "GK", "flag": "kamerun", "name": "Onana"},
            {"pos": "CB", "flag": "italya", "name": "Darmian"},
            {"pos": "CB", "flag": "italya", "name": "Acerbi"},
            {"pos": "CB", "flag": "slovakya", "name": "Skriniar"},
            {"pos": "RB", "flag": "hollanda", "name": "Dumfries"},
            {"pos": "LB", "flag": "italya", "name": "Dimarco"},
            {"pos": "CM", "flag": "turkiye", "name": "Calhanoglu"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Brozovic"},
            {"pos": "CM", "flag": "italya", "name": "Barella"},
            {"pos": "ST", "flag": "arjantin", "name": "Lautaro"},
            {"pos": "ST", "flag": "bosna", "name": "Dzeko"},
        ],
        "options": ["Inter Milan", "AC Milan", "Napoli", "Juventus"],
        "answer": 0
    },
    {
        "name": "AC Milan", "year": "2007",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Dida"},
            {"pos": "RB", "flag": "italya", "name": "Oddo"},
            {"pos": "CB", "flag": "italya", "name": "Nesta"},
            {"pos": "CB", "flag": "italya", "name": "Maldini"},
            {"pos": "LB", "flag": "brezilya", "name": "Jankulovski"},
            {"pos": "CM", "flag": "italya", "name": "Pirlo"},
            {"pos": "CM", "flag": "italya", "name": "Gattuso"},
            {"pos": "CM", "flag": "italya", "name": "Ambrosini"},
            {"pos": "AM", "flag": "brezilya", "name": "Kaka"},
            {"pos": "ST", "flag": "italya", "name": "Inzaghi"},
            {"pos": "LW", "flag": "hollanda", "name": "Seedorf"},
        ],
        "options": ["Inter Milan", "AC Milan", "Roma", "Juventus"],
        "answer": 1
    },
    {
        "name": "Manchester City", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Ederson"},
            {"pos": "RB", "flag": "ingiltere", "name": "Walker"},
            {"pos": "CB", "flag": "fransa", "name": "Laporte"},
            {"pos": "CB", "flag": "belcika", "name": "Kompany"},
            {"pos": "LB", "flag": "ingiltere", "name": "Delph"},
            {"pos": "CM", "flag": "brezilya", "name": "Fernandinho"},
            {"pos": "CM", "flag": "belcika", "name": "De Bruyne"},
            {"pos": "CM", "flag": "ispanya", "name": "Silva"},
            {"pos": "RW", "flag": "almanya", "name": "Sane"},
            {"pos": "ST", "flag": "arjantin", "name": "Aguero"},
            {"pos": "LW", "flag": "ingiltere", "name": "Sterling"},
        ],
        "options": ["Manchester City", "Liverpool", "Tottenham", "Chelsea"],
        "answer": 0
    },
    {
        "name": "PSG", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Areola"},
            {"pos": "RB", "flag": "brezilya", "name": "Dani Alves"},
            {"pos": "CB", "flag": "brezilya", "name": "Thiago Silva"},
            {"pos": "CB", "flag": "brezilya", "name": "Marquinhos"},
            {"pos": "LB", "flag": "fransa", "name": "Kurzawa"},
            {"pos": "CM", "flag": "italya", "name": "Verratti"},
            {"pos": "CM", "flag": "fransa", "name": "Rabiot"},
            {"pos": "CM", "flag": "almanya", "name": "Draxler"},
            {"pos": "RW", "flag": "fransa", "name": "Mbappe"},
            {"pos": "ST", "flag": "uruguay", "name": "Cavani"},
            {"pos": "LW", "flag": "brezilya", "name": "Neymar"},
        ],
        "options": ["Monaco", "Lyon", "Marseille", "PSG"],
        "answer": 3
    },
    {
        "name": "Atletico Madrid", "year": "2014",
        "players": [
            {"pos": "GK", "flag": "belcika", "name": "Courtois"},
            {"pos": "RB", "flag": "ispanya", "name": "Juanfran"},
            {"pos": "CB", "flag": "uruguay", "name": "Godin"},
            {"pos": "CB", "flag": "brezilya", "name": "Miranda"},
            {"pos": "LB", "flag": "brezilya", "name": "Filipe Luis"},
            {"pos": "CM", "flag": "ispanya", "name": "Gabi"},
            {"pos": "CM", "flag": "portekiz", "name": "Tiago"},
            {"pos": "CM", "flag": "ispanya", "name": "Koke"},
            {"pos": "RW", "flag": "turkiye", "name": "Arda Turan"},
            {"pos": "ST", "flag": "ispanya", "name": "Diego Costa"},
            {"pos": "LW", "flag": "kolombiya", "name": "Falcao"},
        ],
        "options": ["Real Madrid", "Atletico Madrid", "Barcelona", "Sevilla"],
        "answer": 1
    },
    {
        "name": "Juventus", "year": "1996",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Peruzzi"},
            {"pos": "RB", "flag": "italya", "name": "Porrini"},
            {"pos": "CB", "flag": "italya", "name": "Ferrara"},
            {"pos": "CB", "flag": "italya", "name": "Vierchowod"},
            {"pos": "LB", "flag": "italya", "name": "Pessotto"},
            {"pos": "CM", "flag": "fransa", "name": "Deschamps"},
            {"pos": "CM", "flag": "italya", "name": "Conte"},
            {"pos": "CM", "flag": "italya", "name": "Di Livio"},
            {"pos": "AM", "flag": "italya", "name": "Del Piero"},
            {"pos": "ST", "flag": "italya", "name": "Ravanelli"},
            {"pos": "ST", "flag": "italya", "name": "Vialli"},
        ],
        "options": ["AC Milan", "Inter Milan", "Juventus", "Roma"],
        "answer": 2
    },
    {
        "name": "Borussia Dortmund", "year": "1997",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Klos"},
            {"pos": "RB", "flag": "almanya", "name": "Kohler"},
            {"pos": "CB", "flag": "almanya", "name": "Sammer"},
            {"pos": "CB", "flag": "almanya", "name": "Reuter"},
            {"pos": "LB", "flag": "almanya", "name": "Schulz"},
            {"pos": "CM", "flag": "iskocya", "name": "Lambert"},
            {"pos": "CM", "flag": "portekiz", "name": "Paulo Sousa"},
            {"pos": "CM", "flag": "almanya", "name": "Moller"},
            {"pos": "AM", "flag": "almanya", "name": "Heinrich"},
            {"pos": "ST", "flag": "almanya", "name": "Riedle"},
            {"pos": "ST", "flag": "isvicre", "name": "Chapuisat"},
        ],
        "options": ["Bayern Munih", "Borussia Dortmund", "Schalke", "Werder Bremen"],
        "answer": 1
    },
    {
        "name": "Manchester City", "year": "2012",
        "players": [
            {"pos": "GK", "flag": "ingiltere", "name": "Hart"},
            {"pos": "RB", "flag": "ingiltere", "name": "Richards"},
            {"pos": "CB", "flag": "belcika", "name": "Kompany"},
            {"pos": "CB", "flag": "ingiltere", "name": "Lescott"},
            {"pos": "LB", "flag": "fransa", "name": "Clichy"},
            {"pos": "CM", "flag": "ispanya", "name": "Silva"},
            {"pos": "CM", "flag": "fildisi", "name": "Yaya Toure"},
            {"pos": "CM", "flag": "ingiltere", "name": "Barry"},
            {"pos": "RW", "flag": "ingiltere", "name": "Milner"},
            {"pos": "ST", "flag": "arjantin", "name": "Aguero"},
            {"pos": "LW", "flag": "arjantin", "name": "Tevez"},
        ],
        "options": ["Manchester United", "Chelsea", "Manchester City", "Tottenham"],
        "answer": 2
    },
    {
        "name": "Roma", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Alisson"},
            {"pos": "RB", "flag": "brezilya", "name": "Bruno Peres"},
            {"pos": "CB", "flag": "yunanistan", "name": "Manolas"},
            {"pos": "CB", "flag": "arjantin", "name": "Fazio"},
            {"pos": "LB", "flag": "sirbistan", "name": "Kolarov"},
            {"pos": "CM", "flag": "italya", "name": "De Rossi"},
            {"pos": "CM", "flag": "hollanda", "name": "Strootman"},
            {"pos": "CM", "flag": "belcika", "name": "Nainggolan"},
            {"pos": "RW", "flag": "misir", "name": "Salah"},
            {"pos": "ST", "flag": "bosna", "name": "Dzeko"},
            {"pos": "LW", "flag": "brezilya", "name": "Gerson"},
        ],
        "options": ["Lazio", "Roma", "Napoli", "Inter Milan"],
        "answer": 1
    },
    {
        "name": "Sevilla", "year": "2020",
        "players": [
            {"pos": "GK", "flag": "fas", "name": "Bono"},
            {"pos": "RB", "flag": "ispanya", "name": "Jesus Navas"},
            {"pos": "CB", "flag": "fransa", "name": "Kounde"},
            {"pos": "CB", "flag": "brezilya", "name": "Diego Carlos"},
            {"pos": "LB", "flag": "ispanya", "name": "Reguilon"},
            {"pos": "CM", "flag": "brezilya", "name": "Fernando"},
            {"pos": "CM", "flag": "arjantin", "name": "Banega"},
            {"pos": "CM", "flag": "ingiltere", "name": "Jordan"},
            {"pos": "RW", "flag": "fas", "name": "En-Nesyri"},
            {"pos": "ST", "flag": "arjantin", "name": "Ocampos"},
            {"pos": "LW", "flag": "ispanya", "name": "Suso"},
        ],
        "options": ["Sevilla", "Valencia", "Villarreal", "Real Betis"],
        "answer": 0
    },
    {
        "name": "Marseille", "year": "1993",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Barthez"},
            {"pos": "RB", "flag": "fransa", "name": "Angloma"},
            {"pos": "CB", "flag": "fransa", "name": "Desailly"},
            {"pos": "CB", "flag": "fransa", "name": "Boli"},
            {"pos": "LB", "flag": "fransa", "name": "Di Meco"},
            {"pos": "CM", "flag": "fransa", "name": "Deschamps"},
            {"pos": "CM", "flag": "fransa", "name": "Sauzee"},
            {"pos": "CM", "flag": "gana", "name": "Abedi Pele"},
            {"pos": "RW", "flag": "almanya", "name": "Voller"},
            {"pos": "ST", "flag": "hirvatistan", "name": "Boksic"},
            {"pos": "LW", "flag": "fransa", "name": "Pele"},
        ],
        "options": ["PSG", "Lyon", "Marseille", "Monaco"],
        "answer": 2
    },
    {
        "name": "Ajax", "year": "1995",
        "players": [
            {"pos": "GK", "flag": "hollanda", "name": "Van der Sar"},
            {"pos": "RB", "flag": "hollanda", "name": "Reiziger"},
            {"pos": "CB", "flag": "hollanda", "name": "F.de Boer"},
            {"pos": "CB", "flag": "hollanda", "name": "Blind"},
            {"pos": "LB", "flag": "hollanda", "name": "R.de Boer"},
            {"pos": "CM", "flag": "hollanda", "name": "Seedorf"},
            {"pos": "CM", "flag": "hollanda", "name": "Rijkaard"},
            {"pos": "CM", "flag": "hollanda", "name": "Davids"},
            {"pos": "RW", "flag": "hollanda", "name": "Overmars"},
            {"pos": "ST", "flag": "hollanda", "name": "Kluivert"},
            {"pos": "LW", "flag": "nijerya", "name": "Finidi"},
        ],
        "options": ["PSV", "Feyenoord", "Ajax", "AZ Alkmaar"],
        "answer": 2
    },
    {
        "name": "Porto", "year": "2004",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Vitor Baia"},
            {"pos": "RB", "flag": "portekiz", "name": "Paulo Ferreira"},
            {"pos": "CB", "flag": "portekiz", "name": "Carvalho"},
            {"pos": "CB", "flag": "portekiz", "name": "Jorge Costa"},
            {"pos": "LB", "flag": "portekiz", "name": "Nuno Valente"},
            {"pos": "CM", "flag": "portekiz", "name": "Costinha"},
            {"pos": "CM", "flag": "portekiz", "name": "Maniche"},
            {"pos": "CM", "flag": "portekiz", "name": "Deco"},
            {"pos": "RW", "flag": "rusya", "name": "Alenichev"},
            {"pos": "ST", "flag": "brezilya", "name": "Carlos Alberto"},
            {"pos": "LW", "flag": "brezilya", "name": "Derlei"},
        ],
        "options": ["Benfica", "Sporting", "Porto", "Braga"],
        "answer": 2
    },
    {
        "name": "Napoli", "year": "2023",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Meret"},
            {"pos": "RB", "flag": "italya", "name": "Di Lorenzo"},
            {"pos": "CB", "flag": "kore", "name": "Kim"},
            {"pos": "CB", "flag": "kosova", "name": "Rrahmani"},
            {"pos": "LB", "flag": "uruguay", "name": "Olivera"},
            {"pos": "CM", "flag": "slovakya", "name": "Lobotka"},
            {"pos": "CM", "flag": "polonya", "name": "Zielinski"},
            {"pos": "CM", "flag": "kamerun", "name": "Anguissa"},
            {"pos": "RW", "flag": "polonya", "name": "Politano"},
            {"pos": "ST", "flag": "nijerya", "name": "Osimhen"},
            {"pos": "LW", "flag": "gurcistan", "name": "Kvaratskhelia"},
        ],
        "options": ["Napoli", "Inter Milan", "Juventus", "AC Milan"],
        "answer": 0
    },
    {
        "name": "Tottenham", "year": "2019",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Lloris"},
            {"pos": "RB", "flag": "ingiltere", "name": "Trippier"},
            {"pos": "CB", "flag": "belcika", "name": "Alderweireld"},
            {"pos": "CB", "flag": "kolombiya", "name": "Sanchez"},
            {"pos": "LB", "flag": "ingiltere", "name": "Rose"},
            {"pos": "CM", "flag": "fransa", "name": "Sissoko"},
            {"pos": "CM", "flag": "kore", "name": "Son"},
            {"pos": "CM", "flag": "danimarka", "name": "Eriksen"},
            {"pos": "RW", "flag": "ingiltere", "name": "Dele Alli"},
            {"pos": "ST", "flag": "ingiltere", "name": "Kane"},
            {"pos": "LW", "flag": "brezilya", "name": "Lucas Moura"},
        ],
        "options": ["Arsenal", "Chelsea", "Tottenham", "West Ham"],
        "answer": 2
    },
    {
        "name": "Lazio", "year": "2000",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Marchegiani"},
            {"pos": "RB", "flag": "italya", "name": "Pancaro"},
            {"pos": "CB", "flag": "arjantin", "name": "Sensini"},
            {"pos": "CB", "flag": "italya", "name": "Nesta"},
            {"pos": "LB", "flag": "italya", "name": "Favalli"},
            {"pos": "CM", "flag": "arjantin", "name": "Simeone"},
            {"pos": "CM", "flag": "cek", "name": "Nedved"},
            {"pos": "CM", "flag": "arjantin", "name": "Veron"},
            {"pos": "AM", "flag": "sirbistan", "name": "Stankovic"},
            {"pos": "ST", "flag": "sili", "name": "Salas"},
            {"pos": "ST", "flag": "italya", "name": "Inzaghi"},
        ],
        "options": ["Roma", "Lazio", "Fiorentina", "Parma"],
        "answer": 1
    },
    {
        "name": "Valencia", "year": "2001",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Canizares"},
            {"pos": "RB", "flag": "fransa", "name": "Angloma"},
            {"pos": "CB", "flag": "arjantin", "name": "Ayala"},
            {"pos": "CB", "flag": "arjantin", "name": "Pellegrino"},
            {"pos": "LB", "flag": "arjantin", "name": "Carboni"},
            {"pos": "CM", "flag": "ispanya", "name": "Baraja"},
            {"pos": "CM", "flag": "ispanya", "name": "Mendieta"},
            {"pos": "CM", "flag": "ispanya", "name": "Albelda"},
            {"pos": "RW", "flag": "norvec", "name": "Carew"},
            {"pos": "ST", "flag": "arjantin", "name": "Aimar"},
            {"pos": "LW", "flag": "ispanya", "name": "Sanchez"},
        ],
        "options": ["Sevilla", "Deportivo", "Valencia", "Villarreal"],
        "answer": 2
    },
    {
        "name": "Monaco", "year": "2017",
        "players": [
            {"pos": "GK", "flag": "hirvatistan", "name": "Subasic"},
            {"pos": "RB", "flag": "fransa", "name": "Sidibe"},
            {"pos": "CB", "flag": "brezilya", "name": "Jemerson"},
            {"pos": "CB", "flag": "polonya", "name": "Glik"},
            {"pos": "LB", "flag": "fransa", "name": "Mendy"},
            {"pos": "CM", "flag": "fransa", "name": "Bakayoko"},
            {"pos": "CM", "flag": "brezilya", "name": "Fabinho"},
            {"pos": "CM", "flag": "portekiz", "name": "B.Silva"},
            {"pos": "RW", "flag": "fransa", "name": "Lemar"},
            {"pos": "ST", "flag": "fransa", "name": "Mbappe"},
            {"pos": "LW", "flag": "kolombiya", "name": "Falcao"},
        ],
        "options": ["PSG", "Lyon", "Marseille", "Monaco"],
        "answer": 3
    },
    {
        "name": "Leverkusen", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "finlandiya", "name": "Hradecky"},
            {"pos": "RB", "flag": "hollanda", "name": "Frimpong"},
            {"pos": "CB", "flag": "almanya", "name": "Tah"},
            {"pos": "CB", "flag": "ekvador", "name": "Hincapie"},
            {"pos": "LB", "flag": "ispanya", "name": "Grimaldo"},
            {"pos": "CM", "flag": "almanya", "name": "Andrich"},
            {"pos": "CM", "flag": "arjantin", "name": "Palacios"},
            {"pos": "CM", "flag": "isvicre", "name": "Xhaka"},
            {"pos": "AM", "flag": "almanya", "name": "Wirtz"},
            {"pos": "ST", "flag": "nijerya", "name": "Boniface"},
            {"pos": "LW", "flag": "almanya", "name": "Hofmann"},
        ],
        "options": ["Bayern Munih", "Dortmund", "Leverkusen", "Leipzig"],
        "answer": 2
    },
    {
        "name": "Manchester City", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Ederson"},
            {"pos": "RB", "flag": "ingiltere", "name": "Walker"},
            {"pos": "CB", "flag": "portekiz", "name": "Dias"},
            {"pos": "CB", "flag": "ingiltere", "name": "Stones"},
            {"pos": "LB", "flag": "hollanda", "name": "Ake"},
            {"pos": "CM", "flag": "ispanya", "name": "Rodri"},
            {"pos": "CM", "flag": "belcika", "name": "De Bruyne"},
            {"pos": "CM", "flag": "portekiz", "name": "B.Silva"},
            {"pos": "RW", "flag": "ingiltere", "name": "Foden"},
            {"pos": "ST", "flag": "norvec", "name": "Haaland"},
            {"pos": "LW", "flag": "arjantin", "name": "Alvarez"},
        ],
        "options": ["Manchester City", "Liverpool", "Arsenal", "Chelsea"],
        "answer": 0
    },
    {
        "name": "Arsenal", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Raya"},
            {"pos": "RB", "flag": "ingiltere", "name": "White"},
            {"pos": "CB", "flag": "fransa", "name": "Saliba"},
            {"pos": "CB", "flag": "brezilya", "name": "Gabriel"},
            {"pos": "LB", "flag": "ukrayna", "name": "Zinchenko"},
            {"pos": "CM", "flag": "ingiltere", "name": "Rice"},
            {"pos": "CM", "flag": "norvec", "name": "Odegaard"},
            {"pos": "CM", "flag": "isvicre", "name": "Havertz"},
            {"pos": "RW", "flag": "ingiltere", "name": "Saka"},
            {"pos": "ST", "flag": "brezilya", "name": "Jesus"},
            {"pos": "LW", "flag": "brezilya", "name": "Martinelli"},
        ],
        "options": ["Manchester United", "Chelsea", "Tottenham", "Arsenal"],
        "answer": 3
    },
    {
        "name": "Real Madrid", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "belcika", "name": "Courtois"},
            {"pos": "RB", "flag": "ispanya", "name": "Carvajal"},
            {"pos": "CB", "flag": "almanya", "name": "Rudiger"},
            {"pos": "CB", "flag": "avusturya", "name": "Alaba"},
            {"pos": "LB", "flag": "fransa", "name": "Mendy"},
            {"pos": "CM", "flag": "fransa", "name": "Tchouameni"},
            {"pos": "CM", "flag": "almanya", "name": "Kroos"},
            {"pos": "CM", "flag": "ingiltere", "name": "Bellingham"},
            {"pos": "RW", "flag": "turkiye", "name": "Arda Guler"},
            {"pos": "ST", "flag": "brezilya", "name": "Vinicius"},
            {"pos": "LW", "flag": "brezilya", "name": "Rodrygo"},
        ],
        "options": ["Barcelona", "Real Madrid", "Atletico", "Sevilla"],
        "answer": 1
    },
    {
        "name": "Bayern Munih", "year": "2001",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Kahn"},
            {"pos": "RB", "flag": "almanya", "name": "Sagnol"},
            {"pos": "CB", "flag": "almanya", "name": "Kuffour"},
            {"pos": "CB", "flag": "almanya", "name": "Linke"},
            {"pos": "LB", "flag": "fransa", "name": "Lizarazu"},
            {"pos": "CM", "flag": "almanya", "name": "Effenberg"},
            {"pos": "CM", "flag": "almanya", "name": "Hargreaves"},
            {"pos": "CM", "flag": "almanya", "name": "Jeremies"},
            {"pos": "RW", "flag": "almanya", "name": "Salihamidzic"},
            {"pos": "ST", "flag": "almanya", "name": "Elber"},
            {"pos": "LW", "flag": "peru", "name": "Pizarro"},
        ],
        "options": ["Bayern Munih", "Real Madrid", "Manchester United", "Lazio"],
        "answer": 0
    },
    {
        "name": "Chelsea", "year": "2005",
        "players": [
            {"pos": "GK", "flag": "cek", "name": "Cech"},
            {"pos": "RB", "flag": "portekiz", "name": "Ferreira"},
            {"pos": "CB", "flag": "ingiltere", "name": "Terry"},
            {"pos": "CB", "flag": "portekiz", "name": "Carvalho"},
            {"pos": "LB", "flag": "ingiltere", "name": "Cole"},
            {"pos": "CM", "flag": "fransa", "name": "Makelele"},
            {"pos": "CM", "flag": "ingiltere", "name": "Lampard"},
            {"pos": "CM", "flag": "portekiz", "name": "Tiago"},
            {"pos": "RW", "flag": "hollanda", "name": "Robben"},
            {"pos": "ST", "flag": "fildisi", "name": "Drogba"},
            {"pos": "LW", "flag": "ingiltere", "name": "Joe Cole"},
        ],
        "options": ["Chelsea", "Arsenal", "Manchester United", "Liverpool"],
        "answer": 0
    },
    {
        "name": "PSG", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Donnarumma"},
            {"pos": "RB", "flag": "fas", "name": "Hakimi"},
            {"pos": "CB", "flag": "fransa", "name": "Marquinhos"},
            {"pos": "CB", "flag": "portekiz", "name": "Beraldo"},
            {"pos": "LB", "flag": "portekiz", "name": "Mendes"},
            {"pos": "CM", "flag": "portekiz", "name": "Vitinha"},
            {"pos": "CM", "flag": "ispanya", "name": "Fabian"},
            {"pos": "CM", "flag": "fransa", "name": "Zaire-Emery"},
            {"pos": "RW", "flag": "portekiz", "name": "Goncalo Ramos"},
            {"pos": "ST", "flag": "fransa", "name": "Mbappe"},
            {"pos": "LW", "flag": "gurcistan", "name": "Kvaratskhelia"},
        ],
        "options": ["PSG", "Marseille", "Lyon", "Monaco"],
        "answer": 0
    },

    # ==================== TURK TAKIMLARI ====================
    {
        "name": "Galatasaray", "year": "2000",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Taffarel"},
            {"pos": "RB", "flag": "turkiye", "name": "Ergun Penbe"},
            {"pos": "CB", "flag": "turkiye", "name": "Bulent Korkmaz"},
            {"pos": "CB", "flag": "turkiye", "name": "Fatih Akyel"},
            {"pos": "LB", "flag": "turkiye", "name": "Capone"},
            {"pos": "CM", "flag": "romanya", "name": "Hagi"},
            {"pos": "CM", "flag": "turkiye", "name": "Emre Belozoglu"},
            {"pos": "CM", "flag": "romanya", "name": "Popescu"},
            {"pos": "AM", "flag": "turkiye", "name": "Suat Kaya"},
            {"pos": "ST", "flag": "turkiye", "name": "Hakan Sukur"},
            {"pos": "ST", "flag": "turkiye", "name": "Arif Erdem"},
        ],
        "options": ["Fenerbahce", "Galatasaray", "Besiktas", "Trabzonspor"],
        "answer": 1
    },
    {
        "name": "Galatasaray", "year": "2013",
        "players": [
            {"pos": "GK", "flag": "uruguay", "name": "Muslera"},
            {"pos": "RB", "flag": "fildisi", "name": "Eboue"},
            {"pos": "CB", "flag": "kamerun", "name": "Chedjou"},
            {"pos": "CB", "flag": "turkiye", "name": "Semih Kaya"},
            {"pos": "LB", "flag": "turkiye", "name": "Hakan Balta"},
            {"pos": "CM", "flag": "turkiye", "name": "Selcuk Inan"},
            {"pos": "CM", "flag": "brezilya", "name": "Melo"},
            {"pos": "CM", "flag": "hollanda", "name": "Sneijder"},
            {"pos": "RW", "flag": "fas", "name": "Amrabat"},
            {"pos": "ST", "flag": "fildisi", "name": "Drogba"},
            {"pos": "LW", "flag": "turkiye", "name": "Burak Yilmaz"},
        ],
        "options": ["Fenerbahce", "Besiktas", "Galatasaray", "Bursaspor"],
        "answer": 2
    },
    {
        "name": "Galatasaray", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "uruguay", "name": "Muslera"},
            {"pos": "RB", "flag": "fas", "name": "Sacha Boey"},
            {"pos": "CB", "flag": "danimarka", "name": "Nelsson"},
            {"pos": "CB", "flag": "turkiye", "name": "Bardakci"},
            {"pos": "LB", "flag": "turkiye", "name": "Kaan Ayhan"},
            {"pos": "CM", "flag": "uruguay", "name": "Torreira"},
            {"pos": "CM", "flag": "almanya", "name": "Demirbay"},
            {"pos": "AM", "flag": "turkiye", "name": "Kerem Akturkoglu"},
            {"pos": "RW", "flag": "belcika", "name": "Mertens"},
            {"pos": "ST", "flag": "arjantin", "name": "Icardi"},
            {"pos": "LW", "flag": "nijerya", "name": "Zaha"},
        ],
        "options": ["Fenerbahce", "Galatasaray", "Besiktas", "Trabzonspor"],
        "answer": 1
    },
    {
        "name": "Fenerbahce", "year": "2008",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Volkan Demirel"},
            {"pos": "RB", "flag": "turkiye", "name": "Gokhan Gonul"},
            {"pos": "CB", "flag": "brezilya", "name": "Edu"},
            {"pos": "CB", "flag": "uruguay", "name": "Lugano"},
            {"pos": "LB", "flag": "brezilya", "name": "Roberto Carlos"},
            {"pos": "CM", "flag": "turkiye", "name": "Selcuk Sahin"},
            {"pos": "CM", "flag": "turkiye", "name": "Emre Belozoglu"},
            {"pos": "CM", "flag": "brezilya", "name": "Alex"},
            {"pos": "RW", "flag": "ingiltere", "name": "Kazim Kazim"},
            {"pos": "ST", "flag": "brezilya", "name": "Deivid"},
            {"pos": "LW", "flag": "turkiye", "name": "Semih Senturk"},
        ],
        "options": ["Galatasaray", "Besiktas", "Fenerbahce", "Trabzonspor"],
        "answer": 2
    },
    {
        "name": "Fenerbahce", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "hirvatistan", "name": "Livakovic"},
            {"pos": "RB", "flag": "ingiltere", "name": "Osayi-Samuel"},
            {"pos": "CB", "flag": "gana", "name": "Djiku"},
            {"pos": "CB", "flag": "brezilya", "name": "Becao"},
            {"pos": "LB", "flag": "turkiye", "name": "Ferdi Kadioglu"},
            {"pos": "CM", "flag": "fas", "name": "Amrabat"},
            {"pos": "CM", "flag": "turkiye", "name": "Ismail Yuksek"},
            {"pos": "CM", "flag": "polonya", "name": "Szymanski"},
            {"pos": "RW", "flag": "sirbistan", "name": "Tadic"},
            {"pos": "ST", "flag": "bosna", "name": "Dzeko"},
            {"pos": "LW", "flag": "nijerya", "name": "Fred"},
        ],
        "options": ["Galatasaray", "Fenerbahce", "Besiktas", "Trabzonspor"],
        "answer": 1
    },
    {
        "name": "Besiktas", "year": "2017",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Fabri"},
            {"pos": "RB", "flag": "turkiye", "name": "Gokhan Gonul"},
            {"pos": "CB", "flag": "sili", "name": "Medel"},
            {"pos": "CB", "flag": "sirbistan", "name": "Tosic"},
            {"pos": "LB", "flag": "brezilya", "name": "Adriano"},
            {"pos": "CM", "flag": "kanada", "name": "Atiba"},
            {"pos": "CM", "flag": "turkiye", "name": "Oguzhan Ozyakup"},
            {"pos": "AM", "flag": "brezilya", "name": "Talisca"},
            {"pos": "RW", "flag": "portekiz", "name": "Quaresma"},
            {"pos": "ST", "flag": "kamerun", "name": "Aboubakar"},
            {"pos": "LW", "flag": "turkiye", "name": "Cenk Tosun"},
        ],
        "options": ["Besiktas", "Galatasaray", "Basaksehir", "Trabzonspor"],
        "answer": 0
    },
    {
        "name": "Trabzonspor", "year": "2022",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Ugurcan Cakir"},
            {"pos": "RB", "flag": "turkiye", "name": "Hugo Vieira"},
            {"pos": "CB", "flag": "uruguay", "name": "Pereira"},
            {"pos": "CB", "flag": "isvicre", "name": "Hosseini"},
            {"pos": "LB", "flag": "tunus", "name": "Meras"},
            {"pos": "CM", "flag": "danimarka", "name": "Hamsik"},
            {"pos": "CM", "flag": "yunanistan", "name": "Bakasetas"},
            {"pos": "CM", "flag": "turkiye", "name": "Abdulkadir Omur"},
            {"pos": "RW", "flag": "nijerya", "name": "Nwakaeme"},
            {"pos": "ST", "flag": "tunus", "name": "Bounedjah"},
            {"pos": "LW", "flag": "bosna", "name": "Visca"},
        ],
        "options": ["Fenerbahce", "Galatasaray", "Besiktas", "Trabzonspor"],
        "answer": 3
    },
    {
        "name": "Fenerbahce", "year": "1996",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Engin Ipekoglu"},
            {"pos": "RB", "flag": "turkiye", "name": "Tayfur Havutcu"},
            {"pos": "CB", "flag": "turkiye", "name": "Bulent Uygun"},
            {"pos": "CB", "flag": "turkiye", "name": "Rusen Cetin"},
            {"pos": "LB", "flag": "turkiye", "name": "Ogun Temizkanoglu"},
            {"pos": "CM", "flag": "almanya", "name": "Aykut Kocaman"},
            {"pos": "CM", "flag": "turkiye", "name": "Tarik Daslar"},
            {"pos": "CM", "flag": "almanya", "name": "Uche Okechukwu"},
            {"pos": "AM", "flag": "turkiye", "name": "Saffet Sancakli"},
            {"pos": "ST", "flag": "almanya", "name": "Stefan Kuntz"},
            {"pos": "ST", "flag": "turkiye", "name": "Elvir Bolic"},
        ],
        "options": ["Trabzonspor", "Galatasaray", "Fenerbahce", "Besiktas"],
        "answer": 2
    },
    {
        "name": "Besiktas", "year": "2003",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Oscar Cordoba"},
            {"pos": "RB", "flag": "turkiye", "name": "Ibrahim Akin"},
            {"pos": "CB", "flag": "turkiye", "name": "Ibrahim Toraman"},
            {"pos": "CB", "flag": "kolombiya", "name": "Quintana"},
            {"pos": "LB", "flag": "turkiye", "name": "Ibrahim Uzulmez"},
            {"pos": "CM", "flag": "portekiz", "name": "Sergen Yalcin"},
            {"pos": "CM", "flag": "turkiye", "name": "Ahmet Yildirim"},
            {"pos": "CM", "flag": "turkiye", "name": "Ali Gunes"},
            {"pos": "AM", "flag": "brezilya", "name": "Ahmet Dursun"},
            {"pos": "ST", "flag": "turkiye", "name": "Ilhan Mansiz"},
            {"pos": "ST", "flag": "fildisi", "name": "Pancu"},
        ],
        "options": ["Galatasaray", "Besiktas", "Trabzonspor", "Fenerbahce"],
        "answer": 1
    },
    {
        "name": "Basaksehir", "year": "2020",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Mert Gunok"},
            {"pos": "RB", "flag": "turkiye", "name": "Junior Caicara"},
            {"pos": "CB", "flag": "turkiye", "name": "Alexandru Epureanu"},
            {"pos": "CB", "flag": "turkiye", "name": "Carlos Ponck"},
            {"pos": "LB", "flag": "fransa", "name": "Clichy"},
            {"pos": "CM", "flag": "turkiye", "name": "Mahmut Tekdemir"},
            {"pos": "CM", "flag": "turkiye", "name": "Visca"},
            {"pos": "CM", "flag": "ingiltere", "name": "Demba Ba"},
            {"pos": "AM", "flag": "almanya", "name": "Edin Visca"},
            {"pos": "ST", "flag": "kosova", "name": "Eljif Elmas"},
            {"pos": "ST", "flag": "turkiye", "name": "Adebayor"},
        ],
        "options": ["Trabzonspor", "Basaksehir", "Konyaspor", "Antalyaspor"],
        "answer": 1
    },

    # ==================== MILLI TAKIMLAR ====================
    {
        "name": "Fransa Milli", "year": "1998",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Barthez"},
            {"pos": "RB", "flag": "fransa", "name": "Thuram"},
            {"pos": "CB", "flag": "fransa", "name": "Desailly"},
            {"pos": "CB", "flag": "fransa", "name": "Blanc"},
            {"pos": "LB", "flag": "fransa", "name": "Lizarazu"},
            {"pos": "CM", "flag": "fransa", "name": "Deschamps"},
            {"pos": "CM", "flag": "fransa", "name": "Petit"},
            {"pos": "CM", "flag": "fransa", "name": "Zidane"},
            {"pos": "AM", "flag": "fransa", "name": "Djorkaeff"},
            {"pos": "ST", "flag": "fransa", "name": "Guivarch"},
            {"pos": "ST", "flag": "fransa", "name": "Henry"},
        ],
        "options": ["Brezilya 1998", "Fransa 1998", "Italya 1998", "Hollanda 1998"],
        "answer": 1
    },
    {
        "name": "Brezilya Milli", "year": "2002",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Marcos"},
            {"pos": "RB", "flag": "brezilya", "name": "Cafu"},
            {"pos": "CB", "flag": "brezilya", "name": "Lucio"},
            {"pos": "CB", "flag": "brezilya", "name": "Edmilson"},
            {"pos": "LB", "flag": "brezilya", "name": "Roberto Carlos"},
            {"pos": "CM", "flag": "brezilya", "name": "Gilberto Silva"},
            {"pos": "CM", "flag": "brezilya", "name": "Kleberson"},
            {"pos": "CM", "flag": "brezilya", "name": "Rivaldo"},
            {"pos": "AM", "flag": "brezilya", "name": "Ronaldinho"},
            {"pos": "ST", "flag": "brezilya", "name": "Ronaldo"},
            {"pos": "ST", "flag": "brezilya", "name": "Juninho"},
        ],
        "options": ["Arjantin 2002", "Brezilya 2002", "Almanya 2002", "Turkiye 2002"],
        "answer": 1
    },
    {
        "name": "Almanya Milli", "year": "2014",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Neuer"},
            {"pos": "RB", "flag": "almanya", "name": "Lahm"},
            {"pos": "CB", "flag": "almanya", "name": "Hummels"},
            {"pos": "CB", "flag": "almanya", "name": "Boateng"},
            {"pos": "LB", "flag": "almanya", "name": "Howedes"},
            {"pos": "CM", "flag": "almanya", "name": "Schweinsteiger"},
            {"pos": "CM", "flag": "almanya", "name": "Kroos"},
            {"pos": "CM", "flag": "almanya", "name": "Khedira"},
            {"pos": "AM", "flag": "almanya", "name": "Ozil"},
            {"pos": "ST", "flag": "almanya", "name": "Klose"},
            {"pos": "ST", "flag": "almanya", "name": "Muller"},
        ],
        "options": ["Almanya 2014", "Almanya 2006", "Almanya 2010", "Almanya 2018"],
        "answer": 0
    },
    {
        "name": "Ispanya Milli", "year": "2010",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Casillas"},
            {"pos": "RB", "flag": "ispanya", "name": "Ramos"},
            {"pos": "CB", "flag": "ispanya", "name": "Pique"},
            {"pos": "CB", "flag": "ispanya", "name": "Puyol"},
            {"pos": "LB", "flag": "ispanya", "name": "Capdevila"},
            {"pos": "CM", "flag": "ispanya", "name": "Xavi"},
            {"pos": "CM", "flag": "ispanya", "name": "Busquets"},
            {"pos": "CM", "flag": "ispanya", "name": "Iniesta"},
            {"pos": "RW", "flag": "ispanya", "name": "Pedro"},
            {"pos": "ST", "flag": "ispanya", "name": "David Villa"},
            {"pos": "LW", "flag": "ispanya", "name": "Torres"},
        ],
        "options": ["Ispanya 2008", "Ispanya 2010", "Ispanya 2012", "Portekiz 2010"],
        "answer": 1
    },
    {
        "name": "Italya Milli", "year": "2006",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Buffon"},
            {"pos": "RB", "flag": "italya", "name": "Zambrotta"},
            {"pos": "CB", "flag": "italya", "name": "Cannavaro"},
            {"pos": "CB", "flag": "italya", "name": "Materazzi"},
            {"pos": "LB", "flag": "italya", "name": "Grosso"},
            {"pos": "CM", "flag": "italya", "name": "Pirlo"},
            {"pos": "CM", "flag": "italya", "name": "Gattuso"},
            {"pos": "CM", "flag": "italya", "name": "De Rossi"},
            {"pos": "AM", "flag": "italya", "name": "Totti"},
            {"pos": "ST", "flag": "italya", "name": "Toni"},
            {"pos": "ST", "flag": "italya", "name": "Del Piero"},
        ],
        "options": ["Fransa 2006", "Italya 2006", "Almanya 2006", "Portekiz 2006"],
        "answer": 1
    },
    {
        "name": "Arjantin Milli", "year": "2022",
        "players": [
            {"pos": "GK", "flag": "arjantin", "name": "E.Martinez"},
            {"pos": "RB", "flag": "arjantin", "name": "Molina"},
            {"pos": "CB", "flag": "arjantin", "name": "Romero"},
            {"pos": "CB", "flag": "arjantin", "name": "Otamendi"},
            {"pos": "LB", "flag": "arjantin", "name": "Tagliafico"},
            {"pos": "CM", "flag": "arjantin", "name": "De Paul"},
            {"pos": "CM", "flag": "arjantin", "name": "Enzo"},
            {"pos": "CM", "flag": "arjantin", "name": "Mac Allister"},
            {"pos": "RW", "flag": "arjantin", "name": "Di Maria"},
            {"pos": "ST", "flag": "arjantin", "name": "Messi"},
            {"pos": "LW", "flag": "arjantin", "name": "Alvarez"},
        ],
        "options": ["Arjantin 2022", "Arjantin 2014", "Uruguay 2022", "Brezilya 2022"],
        "answer": 0
    },
    {
        "name": "Hollanda Milli", "year": "2010",
        "players": [
            {"pos": "GK", "flag": "hollanda", "name": "Stekelenburg"},
            {"pos": "RB", "flag": "hollanda", "name": "Van der Wiel"},
            {"pos": "CB", "flag": "hollanda", "name": "Heitinga"},
            {"pos": "CB", "flag": "hollanda", "name": "Mathijsen"},
            {"pos": "LB", "flag": "hollanda", "name": "Van Bronckhorst"},
            {"pos": "CM", "flag": "hollanda", "name": "Van Bommel"},
            {"pos": "CM", "flag": "hollanda", "name": "De Jong"},
            {"pos": "AM", "flag": "hollanda", "name": "Sneijder"},
            {"pos": "RW", "flag": "hollanda", "name": "Kuyt"},
            {"pos": "ST", "flag": "hollanda", "name": "Van Persie"},
            {"pos": "LW", "flag": "hollanda", "name": "Robben"},
        ],
        "options": ["Hollanda 2010", "Hollanda 2014", "Belcika 2010", "Almanya 2010"],
        "answer": 0
    },
    {
        "name": "Portekiz Milli", "year": "2016",
        "players": [
            {"pos": "GK", "flag": "portekiz", "name": "Rui Patricio"},
            {"pos": "RB", "flag": "portekiz", "name": "Cedric"},
            {"pos": "CB", "flag": "portekiz", "name": "Pepe"},
            {"pos": "CB", "flag": "portekiz", "name": "Fonte"},
            {"pos": "LB", "flag": "portekiz", "name": "Guerreiro"},
            {"pos": "CM", "flag": "portekiz", "name": "Mario"},
            {"pos": "CM", "flag": "portekiz", "name": "Carvalho"},
            {"pos": "CM", "flag": "portekiz", "name": "Adrien"},
            {"pos": "AM", "flag": "portekiz", "name": "Joao Mario"},
            {"pos": "ST", "flag": "portekiz", "name": "Nani"},
            {"pos": "ST", "flag": "portekiz", "name": "Ronaldo"},
        ],
        "options": ["Portekiz 2004", "Portekiz 2016", "Ispanya 2016", "Fransa 2016"],
        "answer": 1
    },
    {
        "name": "Hirvatistan Milli", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "hirvatistan", "name": "Subasic"},
            {"pos": "RB", "flag": "hirvatistan", "name": "Vrsaljko"},
            {"pos": "CB", "flag": "hirvatistan", "name": "Lovren"},
            {"pos": "CB", "flag": "hirvatistan", "name": "Vida"},
            {"pos": "LB", "flag": "hirvatistan", "name": "Strinic"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Brozovic"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Modric"},
            {"pos": "CM", "flag": "hirvatistan", "name": "Rakitic"},
            {"pos": "RW", "flag": "hirvatistan", "name": "Rebic"},
            {"pos": "ST", "flag": "hirvatistan", "name": "Mandzukic"},
            {"pos": "LW", "flag": "hirvatistan", "name": "Perisic"},
        ],
        "options": ["Hirvatistan 2018", "Sirbistan 2018", "Bosna 2018", "Slovenya 2018"],
        "answer": 0
    },
    {
        "name": "Belcika Milli", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "belcika", "name": "Courtois"},
            {"pos": "RB", "flag": "belcika", "name": "Meunier"},
            {"pos": "CB", "flag": "belcika", "name": "Alderweireld"},
            {"pos": "CB", "flag": "belcika", "name": "Kompany"},
            {"pos": "CB", "flag": "belcika", "name": "Vertonghen"},
            {"pos": "LB", "flag": "belcika", "name": "Carrasco"},
            {"pos": "CM", "flag": "belcika", "name": "Witsel"},
            {"pos": "CM", "flag": "belcika", "name": "De Bruyne"},
            {"pos": "AM", "flag": "belcika", "name": "Hazard"},
            {"pos": "ST", "flag": "belcika", "name": "Lukaku"},
            {"pos": "RW", "flag": "belcika", "name": "Mertens"},
        ],
        "options": ["Belcika 2018", "Hollanda 2018", "Fransa 2018", "Portekiz 2018"],
        "answer": 0
    },
    {
        "name": "Ingiltere Milli", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "ingiltere", "name": "Pickford"},
            {"pos": "RB", "flag": "ingiltere", "name": "Walker"},
            {"pos": "CB", "flag": "ingiltere", "name": "Stones"},
            {"pos": "CB", "flag": "ingiltere", "name": "Maguire"},
            {"pos": "LB", "flag": "ingiltere", "name": "Trippier"},
            {"pos": "CM", "flag": "ingiltere", "name": "Henderson"},
            {"pos": "CM", "flag": "ingiltere", "name": "Lingard"},
            {"pos": "CM", "flag": "ingiltere", "name": "Alli"},
            {"pos": "AM", "flag": "ingiltere", "name": "Young"},
            {"pos": "ST", "flag": "ingiltere", "name": "Kane"},
            {"pos": "ST", "flag": "ingiltere", "name": "Sterling"},
        ],
        "options": ["Ingiltere 2018", "Ingiltere 2014", "Galler 2018", "Iskocya 2018"],
        "answer": 0
    },
    {
        "name": "Brezilya Milli", "year": "1998",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Taffarel"},
            {"pos": "RB", "flag": "brezilya", "name": "Cafu"},
            {"pos": "CB", "flag": "brezilya", "name": "Aldair"},
            {"pos": "CB", "flag": "brezilya", "name": "Junior Baiano"},
            {"pos": "LB", "flag": "brezilya", "name": "Roberto Carlos"},
            {"pos": "CM", "flag": "brezilya", "name": "Dunga"},
            {"pos": "CM", "flag": "brezilya", "name": "Cesar Sampaio"},
            {"pos": "AM", "flag": "brezilya", "name": "Rivaldo"},
            {"pos": "AM", "flag": "brezilya", "name": "Leonardo"},
            {"pos": "ST", "flag": "brezilya", "name": "Ronaldo"},
            {"pos": "ST", "flag": "brezilya", "name": "Bebeto"},
        ],
        "options": ["Brezilya 2002", "Brezilya 1998", "Fransa 1998", "Italya 1998"],
        "answer": 1
    },
    {
        "name": "Almanya Milli", "year": "1990",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Illgner"},
            {"pos": "RB", "flag": "almanya", "name": "Reuter"},
            {"pos": "CB", "flag": "almanya", "name": "Augenthaler"},
            {"pos": "CB", "flag": "almanya", "name": "Kohler"},
            {"pos": "LB", "flag": "almanya", "name": "Brehme"},
            {"pos": "CM", "flag": "almanya", "name": "Buchwald"},
            {"pos": "CM", "flag": "almanya", "name": "Matthaus"},
            {"pos": "CM", "flag": "almanya", "name": "Hassler"},
            {"pos": "AM", "flag": "almanya", "name": "Littbarski"},
            {"pos": "ST", "flag": "almanya", "name": "Klinsmann"},
            {"pos": "ST", "flag": "almanya", "name": "Voller"},
        ],
        "options": ["Almanya 1990", "Almanya 1996", "Italya 1990", "Hollanda 1990"],
        "answer": 0
    },
    {
        "name": "Turkiye Milli", "year": "2002",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Rustu Recber"},
            {"pos": "RB", "flag": "turkiye", "name": "Fatih Akyel"},
            {"pos": "CB", "flag": "turkiye", "name": "Bulent Korkmaz"},
            {"pos": "CB", "flag": "turkiye", "name": "Alpay Ozalan"},
            {"pos": "LB", "flag": "turkiye", "name": "Umit Davala"},
            {"pos": "CM", "flag": "turkiye", "name": "Tugay Kerimoglu"},
            {"pos": "CM", "flag": "turkiye", "name": "Emre Belozoglu"},
            {"pos": "CM", "flag": "turkiye", "name": "Yildiray Basturk"},
            {"pos": "AM", "flag": "turkiye", "name": "Ilhan Mansiz"},
            {"pos": "ST", "flag": "turkiye", "name": "Hakan Sukur"},
            {"pos": "ST", "flag": "turkiye", "name": "Hasan Sas"},
        ],
        "options": ["Turkiye 2008", "Turkiye 2002", "Turkiye 2000", "G.Kore 2002"],
        "answer": 1
    },
    {
        "name": "Turkiye Milli", "year": "2008",
        "players": [
            {"pos": "GK", "flag": "turkiye", "name": "Volkan Demirel"},
            {"pos": "RB", "flag": "turkiye", "name": "Sabri Sarioglu"},
            {"pos": "CB", "flag": "turkiye", "name": "Servet Cetin"},
            {"pos": "CB", "flag": "turkiye", "name": "Emre Asik"},
            {"pos": "LB", "flag": "turkiye", "name": "Hakan Balta"},
            {"pos": "CM", "flag": "turkiye", "name": "Mehmet Aurelio"},
            {"pos": "CM", "flag": "turkiye", "name": "Tuncay Sanli"},
            {"pos": "CM", "flag": "turkiye", "name": "Hamit Altintop"},
            {"pos": "AM", "flag": "turkiye", "name": "Arda Turan"},
            {"pos": "ST", "flag": "turkiye", "name": "Nihat Kahveci"},
            {"pos": "ST", "flag": "turkiye", "name": "Semih Senturk"},
        ],
        "options": ["Turkiye 2002", "Turkiye 2008", "Turkiye 2016", "Turkiye 2020"],
        "answer": 1
    },
    {
        "name": "Ispanya Milli", "year": "2024",
        "players": [
            {"pos": "GK", "flag": "ispanya", "name": "Unai Simon"},
            {"pos": "RB", "flag": "ispanya", "name": "Carvajal"},
            {"pos": "CB", "flag": "ispanya", "name": "Le Normand"},
            {"pos": "CB", "flag": "ispanya", "name": "Laporte"},
            {"pos": "LB", "flag": "ispanya", "name": "Cucurella"},
            {"pos": "CM", "flag": "ispanya", "name": "Rodri"},
            {"pos": "CM", "flag": "ispanya", "name": "Fabian Ruiz"},
            {"pos": "AM", "flag": "ispanya", "name": "Dani Olmo"},
            {"pos": "RW", "flag": "ispanya", "name": "Lamine Yamal"},
            {"pos": "ST", "flag": "ispanya", "name": "Morata"},
            {"pos": "LW", "flag": "ispanya", "name": "Nico Williams"},
        ],
        "options": ["Ispanya 2024", "Ispanya 2012", "Almanya 2024", "Fransa 2024"],
        "answer": 0
    },
    {
        "name": "Fransa Milli", "year": "2018",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Lloris"},
            {"pos": "RB", "flag": "fransa", "name": "Pavard"},
            {"pos": "CB", "flag": "fransa", "name": "Varane"},
            {"pos": "CB", "flag": "fransa", "name": "Umtiti"},
            {"pos": "LB", "flag": "fransa", "name": "Hernandez"},
            {"pos": "CM", "flag": "fransa", "name": "Pogba"},
            {"pos": "CM", "flag": "fransa", "name": "Kante"},
            {"pos": "CM", "flag": "fransa", "name": "Matuidi"},
            {"pos": "RW", "flag": "fransa", "name": "Mbappe"},
            {"pos": "ST", "flag": "fransa", "name": "Giroud"},
            {"pos": "LW", "flag": "fransa", "name": "Griezmann"},
        ],
        "options": ["Fransa 2018", "Hirvatistan 2018", "Belcika 2018", "Brezilya 2018"],
        "answer": 0
    },
    {
        "name": "Uruguay Milli", "year": "2010",
        "players": [
            {"pos": "GK", "flag": "uruguay", "name": "Muslera"},
            {"pos": "RB", "flag": "uruguay", "name": "Maxi Pereira"},
            {"pos": "CB", "flag": "uruguay", "name": "Lugano"},
            {"pos": "CB", "flag": "uruguay", "name": "Godin"},
            {"pos": "LB", "flag": "uruguay", "name": "Fucile"},
            {"pos": "CM", "flag": "uruguay", "name": "Diego Perez"},
            {"pos": "CM", "flag": "uruguay", "name": "Egidio Arevalo"},
            {"pos": "CM", "flag": "uruguay", "name": "Diego Forlan"},
            {"pos": "AM", "flag": "uruguay", "name": "Cavani"},
            {"pos": "ST", "flag": "uruguay", "name": "Suarez"},
            {"pos": "LW", "flag": "uruguay", "name": "Alvaro Pereira"},
        ],
        "options": ["Uruguay 2010", "Arjantin 2010", "Brezilya 2010", "Sili 2010"],
        "answer": 0
    },
    {
        "name": "Almanya Milli", "year": "1996",
        "players": [
            {"pos": "GK", "flag": "almanya", "name": "Kopke"},
            {"pos": "RB", "flag": "almanya", "name": "Babbel"},
            {"pos": "CB", "flag": "almanya", "name": "Sammer"},
            {"pos": "CB", "flag": "almanya", "name": "Helmer"},
            {"pos": "LB", "flag": "almanya", "name": "Reuter"},
            {"pos": "CM", "flag": "almanya", "name": "Hassler"},
            {"pos": "CM", "flag": "almanya", "name": "Eilts"},
            {"pos": "CM", "flag": "almanya", "name": "Scholl"},
            {"pos": "AM", "flag": "almanya", "name": "Moller"},
            {"pos": "ST", "flag": "almanya", "name": "Klinsmann"},
            {"pos": "ST", "flag": "almanya", "name": "Bierhoff"},
        ],
        "options": ["Almanya 1996", "Almanya 1990", "Cek 1996", "Italya 1996"],
        "answer": 0
    },
    {
        "name": "Italya Milli", "year": "2020",
        "players": [
            {"pos": "GK", "flag": "italya", "name": "Donnarumma"},
            {"pos": "RB", "flag": "italya", "name": "Di Lorenzo"},
            {"pos": "CB", "flag": "italya", "name": "Bonucci"},
            {"pos": "CB", "flag": "italya", "name": "Chiellini"},
            {"pos": "LB", "flag": "italya", "name": "Spinazzola"},
            {"pos": "CM", "flag": "italya", "name": "Jorginho"},
            {"pos": "CM", "flag": "italya", "name": "Verratti"},
            {"pos": "CM", "flag": "italya", "name": "Barella"},
            {"pos": "AM", "flag": "italya", "name": "Insigne"},
            {"pos": "ST", "flag": "italya", "name": "Immobile"},
            {"pos": "LW", "flag": "italya", "name": "Chiesa"},
        ],
        "options": ["Italya 2020", "Italya 2006", "Ispanya 2020", "Ingiltere 2020"],
        "answer": 0
    },
    {
        "name": "Yunanistan Milli", "year": "2004",
        "players": [
            {"pos": "GK", "flag": "yunanistan", "name": "Nikopolidis"},
            {"pos": "RB", "flag": "yunanistan", "name": "Seitaridis"},
            {"pos": "CB", "flag": "yunanistan", "name": "Dellas"},
            {"pos": "CB", "flag": "yunanistan", "name": "Kapsis"},
            {"pos": "LB", "flag": "yunanistan", "name": "Fyssas"},
            {"pos": "CM", "flag": "yunanistan", "name": "Karagounis"},
            {"pos": "CM", "flag": "yunanistan", "name": "Zagorakis"},
            {"pos": "CM", "flag": "yunanistan", "name": "Basinas"},
            {"pos": "AM", "flag": "yunanistan", "name": "Giannakopoulos"},
            {"pos": "ST", "flag": "yunanistan", "name": "Charisteas"},
            {"pos": "ST", "flag": "yunanistan", "name": "Vryzas"},
        ],
        "options": ["Portekiz 2004", "Yunanistan 2004", "Cek 2004", "Hollanda 2004"],
        "answer": 1
    },
    {
        "name": "Brezilya Milli", "year": "1970",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Felix"},
            {"pos": "RB", "flag": "brezilya", "name": "Carlos Alberto"},
            {"pos": "CB", "flag": "brezilya", "name": "Brito"},
            {"pos": "CB", "flag": "brezilya", "name": "Piazza"},
            {"pos": "LB", "flag": "brezilya", "name": "Everaldo"},
            {"pos": "CM", "flag": "brezilya", "name": "Clodoaldo"},
            {"pos": "CM", "flag": "brezilya", "name": "Gerson"},
            {"pos": "AM", "flag": "brezilya", "name": "Rivelino"},
            {"pos": "RW", "flag": "brezilya", "name": "Jairzinho"},
            {"pos": "ST", "flag": "brezilya", "name": "Pele"},
            {"pos": "LW", "flag": "brezilya", "name": "Tostao"},
        ],
        "options": ["Brezilya 1970", "Brezilya 1962", "Italya 1970", "Almanya 1970"],
        "answer": 0
    },
    {
        "name": "Hollanda Milli", "year": "1988",
        "players": [
            {"pos": "GK", "flag": "hollanda", "name": "Van Breukelen"},
            {"pos": "RB", "flag": "hollanda", "name": "Van Aerle"},
            {"pos": "CB", "flag": "hollanda", "name": "R.Koeman"},
            {"pos": "CB", "flag": "hollanda", "name": "Rijkaard"},
            {"pos": "LB", "flag": "hollanda", "name": "Van Tiggelen"},
            {"pos": "CM", "flag": "hollanda", "name": "Wouters"},
            {"pos": "CM", "flag": "hollanda", "name": "Vanenburg"},
            {"pos": "CM", "flag": "hollanda", "name": "E.Koeman"},
            {"pos": "AM", "flag": "hollanda", "name": "Muhren"},
            {"pos": "ST", "flag": "hollanda", "name": "Van Basten"},
            {"pos": "ST", "flag": "hollanda", "name": "Gullit"},
        ],
        "options": ["Hollanda 1988", "Almanya 1988", "Italya 1988", "Sovyetler 1988"],
        "answer": 0
    },
    {
        "name": "Arjantin Milli", "year": "1986",
        "players": [
            {"pos": "GK", "flag": "arjantin", "name": "Pumpido"},
            {"pos": "RB", "flag": "arjantin", "name": "Cuciuffo"},
            {"pos": "CB", "flag": "arjantin", "name": "Brown"},
            {"pos": "CB", "flag": "arjantin", "name": "Ruggeri"},
            {"pos": "LB", "flag": "arjantin", "name": "Garre"},
            {"pos": "CM", "flag": "arjantin", "name": "Giusti"},
            {"pos": "CM", "flag": "arjantin", "name": "Batista"},
            {"pos": "CM", "flag": "arjantin", "name": "Burruchaga"},
            {"pos": "AM", "flag": "arjantin", "name": "Maradona"},
            {"pos": "ST", "flag": "arjantin", "name": "Valdano"},
            {"pos": "ST", "flag": "arjantin", "name": "Enrique"},
        ],
        "options": ["Arjantin 1986", "Brezilya 1986", "Almanya 1986", "Ingiltere 1986"],
        "answer": 0
    },
    {
        "name": "Ingiltere Milli", "year": "1966",
        "players": [
            {"pos": "GK", "flag": "ingiltere", "name": "Banks"},
            {"pos": "RB", "flag": "ingiltere", "name": "Cohen"},
            {"pos": "CB", "flag": "ingiltere", "name": "J.Charlton"},
            {"pos": "CB", "flag": "ingiltere", "name": "Moore"},
            {"pos": "LB", "flag": "ingiltere", "name": "Wilson"},
            {"pos": "CM", "flag": "ingiltere", "name": "Stiles"},
            {"pos": "CM", "flag": "ingiltere", "name": "B.Charlton"},
            {"pos": "CM", "flag": "ingiltere", "name": "Peters"},
            {"pos": "RW", "flag": "ingiltere", "name": "Ball"},
            {"pos": "ST", "flag": "ingiltere", "name": "Hurst"},
            {"pos": "LW", "flag": "ingiltere", "name": "Hunt"},
        ],
        "options": ["Ingiltere 1966", "Almanya 1966", "Brezilya 1966", "Italya 1966"],
        "answer": 0
    },
    {
        "name": "Brezilya Milli", "year": "1994",
        "players": [
            {"pos": "GK", "flag": "brezilya", "name": "Taffarel"},
            {"pos": "RB", "flag": "brezilya", "name": "Jorginho"},
            {"pos": "CB", "flag": "brezilya", "name": "Aldair"},
            {"pos": "CB", "flag": "brezilya", "name": "Marcio Santos"},
            {"pos": "LB", "flag": "brezilya", "name": "Branco"},
            {"pos": "CM", "flag": "brezilya", "name": "Mauro Silva"},
            {"pos": "CM", "flag": "brezilya", "name": "Dunga"},
            {"pos": "CM", "flag": "brezilya", "name": "Mazinho"},
            {"pos": "AM", "flag": "brezilya", "name": "Zinho"},
            {"pos": "ST", "flag": "brezilya", "name": "Romario"},
            {"pos": "ST", "flag": "brezilya", "name": "Bebeto"},
        ],
        "options": ["Brezilya 1994", "Italya 1994", "Almanya 1994", "Arjantin 1994"],
        "answer": 0
    },
    {
        "name": "Fransa Milli", "year": "2022",
        "players": [
            {"pos": "GK", "flag": "fransa", "name": "Lloris"},
            {"pos": "RB", "flag": "fransa", "name": "Kounde"},
            {"pos": "CB", "flag": "fransa", "name": "Varane"},
            {"pos": "CB", "flag": "fransa", "name": "Upamecano"},
            {"pos": "LB", "flag": "fransa", "name": "Theo Hernandez"},
            {"pos": "CM", "flag": "fransa", "name": "Tchouameni"},
            {"pos": "CM", "flag": "fransa", "name": "Rabiot"},
            {"pos": "AM", "flag": "fransa", "name": "Griezmann"},
            {"pos": "RW", "flag": "fransa", "name": "Dembele"},
            {"pos": "ST", "flag": "fransa", "name": "Giroud"},
            {"pos": "LW", "flag": "fransa", "name": "Mbappe"},
        ],
        "options": ["Fransa 2022", "Arjantin 2022", "Hirvatistan 2022", "Fas 2022"],
        "answer": 0
    },
    {
        "name": "Fas Milli", "year": "2022",
        "players": [
            {"pos": "GK", "flag": "fas", "name": "Bono"},
            {"pos": "RB", "flag": "fas", "name": "Hakimi"},
            {"pos": "CB", "flag": "fas", "name": "Saiss"},
            {"pos": "CB", "flag": "fas", "name": "Aguerd"},
            {"pos": "LB", "flag": "fas", "name": "Mazraoui"},
            {"pos": "CM", "flag": "fas", "name": "Amrabat"},
            {"pos": "CM", "flag": "fas", "name": "Ounahi"},
            {"pos": "CM", "flag": "fas", "name": "Amallah"},
            {"pos": "RW", "flag": "fas", "name": "Ziyech"},
            {"pos": "ST", "flag": "fas", "name": "En-Nesyri"},
            {"pos": "LW", "flag": "fas", "name": "Boufal"},
        ],
        "options": ["Fas 2022", "Tunus 2022", "Senegal 2022", "Cezayir 2022"],
        "answer": 0
    },
]